<div class="row">
<div class="col-md-12">
<div class="box">
    <div class="box-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr class="titulo">
                    <th width="60px">ID</th>
                    <th>Tipo</th>
                    <th>Descrição</th>
                    <th>Nome Classe</th>
                    <th>Intervalo (Minutos)</th>
                    <th>Última Execução</th>
                    <th>Status</th>
                    <th class="btn_titulo"></th>
                </tr>
            </thead>
            <tbody>
<?php if (isset($this->result["registros"]) && !empty($this->result["registros"])) { ?>
<?php 
foreach ($this->result["registros"] as $registro) {
    $txt_id = $txt_tipo = $txt_descricao = $txt_class_name = $txt_minutos = $txt_ultima_execucao = $txt_status = "--";
    if (isset($registro["id"]) && $registro["id"]) {
        $txt_id = $registro["id"]; 
        $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
    }
    if (isset($registro["tostring"]) && $registro["tostring"]) { $txt_descricao = $registro["tostring"]; }
    if (isset($registro["observador_tipo"]["descricao"]) && $registro["observador_tipo"]["descricao"]) { $txt_tipo = $registro["observador_tipo"]["descricao"]; }
    if (isset($registro["class_name"]) && $registro["class_name"]) { $txt_class_name = $registro["class_name"]; }
    if (isset($registro["minutos"]) && $registro["minutos"]) { $txt_minutos = $registro["minutos"]; }
    if (isset($registro["data_ultima_execucao"]) && $registro["data_ultima_execucao"]) { $txt_ultima_execucao = $registro["data_ultima_execucao"]; }
    if (isset($registro["status"]) && $registro["status"]) {
        $txt_status = "INATIVO";
        if ($registro["status"] == "A") {
            $txt_status = "ATIVO";
        }
    }
?>
            <tr>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_tipo; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_descricao; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_class_name; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_minutos; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_ultima_execucao; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_status; ?></a></td>
                <td>
                    <div class="btn-group pull-right">
                        <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                        <a class="btn btn-default" title="Editar" href="<?php echo $this->url(null, array("action" => "editar", "id" => $txt_id), true); ?>"><i class="fa fa-cogs"></i></a>
                        <a class="btn btn-default link_confirma" title="Excluir" href="<?php echo $this->url(null, array("action" => "excluir", "id" => $txt_id), true); ?>"><i class="fa fa-trash-o"></i></a>
                    </div>
                </td>
            </tr>
<?php } ?>
<?php } else { ?>
            <tr>
                <td colspan="6"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
            </tr>
<?php } ?>
            </tbody>
        </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
        <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
        </div>

    </div>
</div>
</div>