<?php
$txt_id = $txt_tipo = $txt_descricao = $txt_class_name = $txt_minutos = $txt_ultima_execucao = $txt_status = "--";
if (isset($this->result)) {
    $registro = $this->result;
    
    if (isset($registro["id"]) && $registro["id"]) {
        $txt_id = $registro["id"]; 
    }
    if (isset($registro["tostring"]) && $registro["tostring"]) { $txt_descricao = $registro["tostring"]; }
    if (isset($registro["observador_tipo"]["descricao"]) && $registro["observador_tipo"]["descricao"]) { $txt_tipo = $registro["observador_tipo"]["descricao"]; }
    if (isset($registro["class_name"]) && $registro["class_name"]) { $txt_class_name = $registro["class_name"]; }
    if (isset($registro["minutos"]) && $registro["minutos"]) { $txt_minutos = $registro["minutos"]; }
    if (isset($registro["data_ultima_execucao"]) && $registro["data_ultima_execucao"]) { $txt_ultima_execucao = $registro["data_ultima_execucao"]; }
    if (isset($registro["status"]) && $registro["status"]) {
        $txt_status = "INATIVO";
        if ($registro["status"] == "A") {
            $txt_status = "ATIVO";
        }
    }
}
?>
<div class="row">
    <div class="col-md-12">
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Visualizar Tipo de Observador</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <dl class="dl-horizontal">
            <dt>ID: </dt>
            <dd><?php echo $txt_id; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tipo: </dt>
            <dd><?php echo $txt_tipo; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Descrição: </dt>
            <dd><?php echo $txt_descricao; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Nome Classe: </dt>
            <dd><?php echo $txt_class_name; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Intervalo (Minutos): </dt>
            <dd><?php echo $txt_minutos; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Última Execução: </dt>
            <dd><?php echo $txt_ultima_execucao; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Status: </dt>
            <dd><?php echo $txt_status; ?></dd>
        </dl>
    </div>
</div>
    </div>
</div>