<?php

namespace DoctrineORMModule\Proxy\__CG__\Marabaixo\Seguranca\Dominio;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Marabaixo\Seguranca\Dominio\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'salt', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'senha', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'status', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'alteraSenha', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'pessoaFisica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'grupos', 'eventos', 'sm', 'em');
        }

        return array('__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'salt', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'senha', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'status', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'alteraSenha', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'pessoaFisica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Usuario' . "\0" . 'grupos', 'eventos', 'sm', 'em');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function postLoad($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postLoad', array($event));

        return parent::postLoad($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaFisica', array());

        return parent::getPessoaFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupos', array());

        return parent::getGrupos();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptPassword($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptPassword', array($senha));

        return parent::encryptPassword($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaFisica(\Marabaixo\Seguranca\Dominio\PessoaFisica $pessoaFisica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaFisica', array($pessoaFisica));

        return parent::setPessoaFisica($pessoaFisica);
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupos(\Doctrine\Common\Collections\Collection $grupos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupos', array($grupos));

        return parent::setGrupos($grupos);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlteraSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlteraSenha', array());

        return parent::getAlteraSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlteraSenha($alteraSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlteraSenha', array($alteraSenha));

        return parent::setAlteraSenha($alteraSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function setFromArray(array $dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromArray', array($dados));

        return parent::setFromArray($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function addGrupo($grupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGrupo', array($grupo));

        return parent::addGrupo($grupo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGrupo($grupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGrupo', array($grupo));

        return parent::removeGrupo($grupo);
    }

    /**
     * {@inheritDoc}
     */
    public function ativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ativo', array());

        return parent::ativo();
    }

    /**
     * {@inheritDoc}
     */
    public function autenticar($dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'autenticar', array($dados));

        return parent::autenticar($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function pegaMeusComponentes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pegaMeusComponentes', array());

        return parent::pegaMeusComponentes();
    }

    /**
     * {@inheritDoc}
     */
    public function carregaPermissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'carregaPermissao', array());

        return parent::carregaPermissao();
    }

    /**
     * {@inheritDoc}
     */
    public function possuiPermissao(array $dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'possuiPermissao', array($dados));

        return parent::possuiPermissao($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function mostrarStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mostrarStatus', array());

        return parent::mostrarStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', array());

        return parent::toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', array());

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function gerarSenhaTemporaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gerarSenhaTemporaria', array());

        return parent::gerarSenhaTemporaria();
    }

    /**
     * {@inheritDoc}
     */
    public function persist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'persist', array());

        return parent::persist();
    }

    /**
     * {@inheritDoc}
     */
    public function alterar_senha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'alterar_senha', array());

        return parent::alterar_senha();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorEmail', array($email));

        return parent::getPorEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function pegaUsuarioLogado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pegaUsuarioLogado', array());

        return parent::pegaUsuarioLogado();
    }

    /**
     * {@inheritDoc}
     */
    public function atualizaGrupos($id_grupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'atualizaGrupos', array($id_grupo));

        return parent::atualizaGrupos($id_grupo);
    }

    /**
     * {@inheritDoc}
     */
    public function administrador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'administrador', array());

        return parent::administrador();
    }

    /**
     * {@inheritDoc}
     */
    public function ativar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ativar', array());

        return parent::ativar();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegiaoAtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegiaoAtual', array());

        return parent::getRegiaoAtual();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryKey', array());

        return parent::getPrimaryKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', array());

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function findAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findAll', array());

        return parent::findAll();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorId', array($id));

        return parent::getPorId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoveErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoveErrors', array());

        return parent::getRemoveErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function postPersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postPersist', array());

        return parent::postPersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuery($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuery', array($dados));

        return parent::getQuery($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listar($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listar', array($dados));

        return parent::listar($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listarPorPagina($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listarPorPagina', array($dados));

        return parent::listarPorPagina($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', array());

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservador', array());

        return parent::getObservador();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', array());

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addObservador($evento, \Marabaixo\Abstrata\AbstractObservador $observador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObservador', array($evento, $observador));

        return parent::addObservador($evento, $observador);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservadores($evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservadores', array($evento));

        return parent::getObservadores($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function notificar($evento, $dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'notificar', array($evento, $dados));

        return parent::notificar($evento, $dados);
    }

    /**
     * {@inheritDoc}
     */
    public function set_em($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_em', array($em));

        return parent::set_em($em);
    }

    /**
     * {@inheritDoc}
     */
    public function get_em()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_em', array());

        return parent::get_em();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceLocator(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceLocator', array($serviceLocator));

        return parent::setServiceLocator($serviceLocator);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceLocator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceLocator', array());

        return parent::getServiceLocator();
    }

}
