<?php

namespace DoctrineORMModule\Proxy\__CG__\Marabaixo\Seguranca\Dominio;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PessoaFisica extends \Marabaixo\Seguranca\Dominio\PessoaFisica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'idPessoaFisica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'cpf', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'passaporte', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nome', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'dataNascimento', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'pais', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nacionalidade', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'pessoa', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeNumero', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeOrgaoEmissor', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nomePai', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nomeMae', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'sexo', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeDataEmissao', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'municipio', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeUf', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'estadoCivil', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'arquivoFoto', 'eventos', 'sm', 'em'];
        }

        return ['__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'idPessoaFisica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'cpf', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'passaporte', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nome', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'dataNascimento', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'pais', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nacionalidade', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'pessoa', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeNumero', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeOrgaoEmissor', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nomePai', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'nomeMae', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'sexo', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeDataEmissao', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'municipio', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'identidadeUf', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'estadoCivil', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaFisica' . "\0" . 'arquivoFoto', 'eventos', 'sm', 'em'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PessoaFisica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPessoaFisica()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPessoaFisica();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPessoaFisica', []);

        return parent::getIdPessoaFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', []);

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassaporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassaporte', []);

        return parent::getPassaporte();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', []);

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidade', []);

        return parent::getNacionalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoa', []);

        return parent::getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPessoaFisica($idPessoaFisica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPessoaFisica', [$idPessoaFisica]);

        return parent::setIdPessoaFisica($idPessoaFisica);
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', [$cpf]);

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassaporte($passaporte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassaporte', [$passaporte]);

        return parent::setPassaporte($passaporte);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento(\DateTime $dataNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', [$dataNascimento]);

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setPais(\Marabaixo\Seguranca\Dominio\Pais $pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidade(\Marabaixo\Seguranca\Dominio\Nacionalidade $nacionalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidade', [$nacionalidade]);

        return parent::setNacionalidade($nacionalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoa(\Marabaixo\Seguranca\Dominio\Pessoa $pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoa', [$pessoa]);

        return parent::setPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentidadeNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentidadeNumero', []);

        return parent::getIdentidadeNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentidadeOrgaoEmissor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentidadeOrgaoEmissor', []);

        return parent::getIdentidadeOrgaoEmissor();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePai', []);

        return parent::getNomePai();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeMae', []);

        return parent::getNomeMae();
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentidadeDataEmissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentidadeDataEmissao', []);

        return parent::getIdentidadeDataEmissao();
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentidadeUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentidadeUf', []);

        return parent::getIdentidadeUf();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoCivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoCivil', []);

        return parent::getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentidadeNumero($identidadeNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentidadeNumero', [$identidadeNumero]);

        return parent::setIdentidadeNumero($identidadeNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentidadeOrgaoEmissor($identidadeOrgaoEmissor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentidadeOrgaoEmissor', [$identidadeOrgaoEmissor]);

        return parent::setIdentidadeOrgaoEmissor($identidadeOrgaoEmissor);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomePai($nomePai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomePai', [$nomePai]);

        return parent::setNomePai($nomePai);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeMae($nomeMae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeMae', [$nomeMae]);

        return parent::setNomeMae($nomeMae);
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentidadeDataEmissao(\DateTime $identidadeDataEmissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentidadeDataEmissao', [$identidadeDataEmissao]);

        return parent::setIdentidadeDataEmissao($identidadeDataEmissao);
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(\Marabaixo\Seguranca\Dominio\Municipio $municipio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentidadeUf(\Marabaixo\Seguranca\Dominio\Uf $identidadeUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentidadeUf', [$identidadeUf]);

        return parent::setIdentidadeUf($identidadeUf);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoCivil(\Marabaixo\Seguranca\Dominio\EstadoCivil $estadoCivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoCivil', [$estadoCivil]);

        return parent::setEstadoCivil($estadoCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getArquivoFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArquivoFoto', []);

        return parent::getArquivoFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setArquivoFoto($arquivoFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArquivoFoto', [$arquivoFoto]);

        return parent::setArquivoFoto($arquivoFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function idadeMaior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'idadeMaior', []);

        return parent::idadeMaior();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromArray(array $dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromArray', [$dados]);

        return parent::setFromArray($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', []);

        return parent::toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function brasileiro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'brasileiro', []);

        return parent::brasileiro();
    }

    /**
     * {@inheritDoc}
     */
    public function naturalizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'naturalizado', []);

        return parent::naturalizado();
    }

    /**
     * {@inheritDoc}
     */
    public function estrangeiro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'estrangeiro', []);

        return parent::estrangeiro();
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', []);

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function persist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'persist', []);

        return parent::persist();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorPessoa($pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorPessoa', [$pessoa]);

        return parent::getPorPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function loadOriginal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadOriginal', []);

        return parent::loadOriginal();
    }

    /**
     * {@inheritDoc}
     */
    public function init($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'init', [$event]);

        return parent::init($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginal', []);

        return parent::getOriginal();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginal($original)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginal', [$original]);

        return parent::setOriginal($original);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryKey', []);

        return parent::getPrimaryKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', []);

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function findAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findAll', []);

        return parent::findAll();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorId', [$id]);

        return parent::getPorId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoveErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoveErrors', []);

        return parent::getRemoveErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function postPersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postPersist', []);

        return parent::postPersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuery($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuery', [$dados]);

        return parent::getQuery($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listar($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listar', [$dados]);

        return parent::listar($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listarPorPagina($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listarPorPagina', [$dados]);

        return parent::listarPorPagina($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function registra_log_salvar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registra_log_salvar', []);

        return parent::registra_log_salvar();
    }

    /**
     * {@inheritDoc}
     */
    public function registra_log_excluir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registra_log_excluir', []);

        return parent::registra_log_excluir();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', []);

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservador', []);

        return parent::getObservador();
    }

    /**
     * {@inheritDoc}
     */
    public function ativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ativo', []);

        return parent::ativo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', []);

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addObservador($evento, \Marabaixo\Abstrata\AbstractObservador $observador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObservador', [$evento, $observador]);

        return parent::addObservador($evento, $observador);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservadores($evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservadores', [$evento]);

        return parent::getObservadores($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function notificar($evento, $dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'notificar', [$evento, $dados]);

        return parent::notificar($evento, $dados);
    }

    /**
     * {@inheritDoc}
     */
    public function set_em($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_em', [$em]);

        return parent::set_em($em);
    }

    /**
     * {@inheritDoc}
     */
    public function get_em()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_em', []);

        return parent::get_em();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceLocator(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceLocator', [$serviceLocator]);

        return parent::setServiceLocator($serviceLocator);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceLocator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceLocator', []);

        return parent::getServiceLocator();
    }

}
