<?php

namespace DoctrineORMModule\Proxy\__CG__\Marabaixo\Seguranca\Dominio;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PessoaJuridica extends \Marabaixo\Seguranca\Dominio\PessoaJuridica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'idPessoaJuridica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'cnpj', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'sigla', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'razaoSocial', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'nomeFantasia', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'arquivoLogo', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'pessoa', 'eventos', 'sm', 'em'];
        }

        return ['__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'idPessoaJuridica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'cnpj', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'sigla', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'razaoSocial', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'nomeFantasia', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'arquivoLogo', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\PessoaJuridica' . "\0" . 'pessoa', 'eventos', 'sm', 'em'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PessoaJuridica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPessoaJuridica()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPessoaJuridica();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPessoaJuridica', []);

        return parent::getIdPessoaJuridica();
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', []);

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function getSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigla', []);

        return parent::getSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function getRazaoSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazaoSocial', []);

        return parent::getRazaoSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeFantasia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeFantasia', []);

        return parent::getNomeFantasia();
    }

    /**
     * {@inheritDoc}
     */
    public function getArquivoLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArquivoLogo', []);

        return parent::getArquivoLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoa', []);

        return parent::getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPessoaJuridica($idPessoaJuridica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPessoaJuridica', [$idPessoaJuridica]);

        return parent::setIdPessoaJuridica($idPessoaJuridica);
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpj($cnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpj', [$cnpj]);

        return parent::setCnpj($cnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function setSigla($sigla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigla', [$sigla]);

        return parent::setSigla($sigla);
    }

    /**
     * {@inheritDoc}
     */
    public function setRazaoSocial($razaoSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazaoSocial', [$razaoSocial]);

        return parent::setRazaoSocial($razaoSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeFantasia($nomeFantasia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeFantasia', [$nomeFantasia]);

        return parent::setNomeFantasia($nomeFantasia);
    }

    /**
     * {@inheritDoc}
     */
    public function setArquivoLogo(\Marabaixo\Seguranca\Dominio\Arquivo $arquivoLogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArquivoLogo', [$arquivoLogo]);

        return parent::setArquivoLogo($arquivoLogo);
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoa(\Marabaixo\Seguranca\Dominio\Pessoa $pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoa', [$pessoa]);

        return parent::setPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function setFromArray(array $dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromArray', [$dados]);

        return parent::setFromArray($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', []);

        return parent::toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', []);

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function persist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'persist', []);

        return parent::persist();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorPessoa($pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorPessoa', [$pessoa]);

        return parent::getPorPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function loadOriginal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadOriginal', []);

        return parent::loadOriginal();
    }

    /**
     * {@inheritDoc}
     */
    public function init($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'init', [$event]);

        return parent::init($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginal', []);

        return parent::getOriginal();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginal($original)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginal', [$original]);

        return parent::setOriginal($original);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryKey', []);

        return parent::getPrimaryKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', []);

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function findAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findAll', []);

        return parent::findAll();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorId', [$id]);

        return parent::getPorId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoveErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoveErrors', []);

        return parent::getRemoveErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function postPersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postPersist', []);

        return parent::postPersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuery($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuery', [$dados]);

        return parent::getQuery($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listar($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listar', [$dados]);

        return parent::listar($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listarPorPagina($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listarPorPagina', [$dados]);

        return parent::listarPorPagina($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function registra_log_salvar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registra_log_salvar', []);

        return parent::registra_log_salvar();
    }

    /**
     * {@inheritDoc}
     */
    public function registra_log_excluir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registra_log_excluir', []);

        return parent::registra_log_excluir();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', []);

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservador', []);

        return parent::getObservador();
    }

    /**
     * {@inheritDoc}
     */
    public function ativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ativo', []);

        return parent::ativo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', []);

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addObservador($evento, \Marabaixo\Abstrata\AbstractObservador $observador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObservador', [$evento, $observador]);

        return parent::addObservador($evento, $observador);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservadores($evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservadores', [$evento]);

        return parent::getObservadores($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function notificar($evento, $dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'notificar', [$evento, $dados]);

        return parent::notificar($evento, $dados);
    }

    /**
     * {@inheritDoc}
     */
    public function set_em($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_em', [$em]);

        return parent::set_em($em);
    }

    /**
     * {@inheritDoc}
     */
    public function get_em()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_em', []);

        return parent::get_em();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceLocator(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceLocator', [$serviceLocator]);

        return parent::setServiceLocator($serviceLocator);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceLocator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceLocator', []);

        return parent::getServiceLocator();
    }

}
