<?php

namespace DoctrineORMModule\Proxy\__CG__\Marabaixo\Seguranca\Dominio;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Config extends \Marabaixo\Seguranca\Dominio\Config implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'idConfig', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'sistemaNome', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'sistemaSigla', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'arquivoLogo', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'pessoaJuridica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'maioridadeIdadeMinima', 'eventos', 'sm', 'em');
        }

        return array('__isInitialized__', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'idConfig', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'sistemaNome', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'sistemaSigla', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'arquivoLogo', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'pessoaJuridica', '' . "\0" . 'Marabaixo\\Seguranca\\Dominio\\Config' . "\0" . 'maioridadeIdadeMinima', 'eventos', 'sm', 'em');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Config $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdConfig()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdConfig();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdConfig', array());

        return parent::getIdConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function getSistemaNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSistemaNome', array());

        return parent::getSistemaNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getSistemaSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSistemaSigla', array());

        return parent::getSistemaSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function getArquivoLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArquivoLogo', array());

        return parent::getArquivoLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaJuridica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaJuridica', array());

        return parent::getPessoaJuridica();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdConfig($idConfig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdConfig', array($idConfig));

        return parent::setIdConfig($idConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function setSistemaNome($sistemaNome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSistemaNome', array($sistemaNome));

        return parent::setSistemaNome($sistemaNome);
    }

    /**
     * {@inheritDoc}
     */
    public function setSistemaSigla($sistemaSigla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSistemaSigla', array($sistemaSigla));

        return parent::setSistemaSigla($sistemaSigla);
    }

    /**
     * {@inheritDoc}
     */
    public function setArquivoLogo(\Marabaixo\Seguranca\Dominio\Arquivo $arquivoLogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArquivoLogo', array($arquivoLogo));

        return parent::setArquivoLogo($arquivoLogo);
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaJuridica(\Marabaixo\Seguranca\Dominio\PessoaJuridica $pessoaJuridica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaJuridica', array($pessoaJuridica));

        return parent::setPessoaJuridica($pessoaJuridica);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaioridadeIdadeMinima()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaioridadeIdadeMinima', array());

        return parent::getMaioridadeIdadeMinima();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaioridadeIdadeMinima($maioridadeIdadeMinima)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaioridadeIdadeMinima', array($maioridadeIdadeMinima));

        return parent::setMaioridadeIdadeMinima($maioridadeIdadeMinima);
    }

    /**
     * {@inheritDoc}
     */
    public function setFromArray(array $dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromArray', array($dados));

        return parent::setFromArray($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigSmtp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfigSmtp', array());

        return parent::getConfigSmtp();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryKey', array());

        return parent::getPrimaryKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', array());

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function findAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findAll', array());

        return parent::findAll();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorId', array($id));

        return parent::getPorId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', array());

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoveErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoveErrors', array());

        return parent::getRemoveErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function persist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'persist', array());

        return parent::persist();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function postPersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postPersist', array());

        return parent::postPersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuery($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuery', array($dados));

        return parent::getQuery($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listar($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listar', array($dados));

        return parent::listar($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function listarPorPagina($dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'listarPorPagina', array($dados));

        return parent::listarPorPagina($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', array());

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservador', array());

        return parent::getObservador();
    }

    /**
     * {@inheritDoc}
     */
    public function ativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ativo', array());

        return parent::ativo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', array());

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addObservador($evento, \Marabaixo\Abstrata\AbstractObservador $observador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObservador', array($evento, $observador));

        return parent::addObservador($evento, $observador);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservadores($evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservadores', array($evento));

        return parent::getObservadores($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function notificar($evento, $dados = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'notificar', array($evento, $dados));

        return parent::notificar($evento, $dados);
    }

    /**
     * {@inheritDoc}
     */
    public function set_em($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_em', array($em));

        return parent::set_em($em);
    }

    /**
     * {@inheritDoc}
     */
    public function get_em()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_em', array());

        return parent::get_em();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceLocator(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceLocator', array($serviceLocator));

        return parent::setServiceLocator($serviceLocator);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceLocator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceLocator', array());

        return parent::getServiceLocator();
    }

}
