<?php
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
    $("#sistema_sigla").focus().select();
});
<?php
$this->inlineScript()->captureEnd();

$form = $this->form;
$form->setAttribute('action', $this->url(null, array("action" => "index"), true));
$form->setAttribute('class', "form-horizontal");

$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="row">
<div class="col-lg-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs">
          <li class="active"><a href="#area1" data-toggle="tab" aria-expanded="true">Configurações do Sistema &raquo;</a></li>
          <li class=""><a href="#area2" data-toggle="tab" aria-expanded="false">Cliente &raquo;</a></li>
          <li class=""><a href="#area3" data-toggle="tab" aria-expanded="false">Configurações SMTP</a></li>
        </ul>
        <br />
        <div class="tab-content no-padding">
          <!-- Morris chart - Sales -->
          <div class="chart tab-pane active" id="area1">
            <?php 
                echo $form->showInput("sistema_sigla", $this, array("col-width" => 2)); 
                echo $form->showInput("sistema_nome", $this, array("col-width" => 4)); 
                $input = $form->get("id_arquivo_logo"); echo $input->render($this); 
                echo $form->showInput("maioridade_idade_minima", $this, array("col-width" => 1));
            ?>
            <div class="form-group">
            <label class="col-sm-2 control-label" for=""></label>            
                <div class="controls">
                    <div class="col-sm-2">
                        <a class="btn btn-primary" href="#area2" data-toggle="tab" aria-expanded="false"><i class="fa fa-arrow-circle-o-right"></i> Proximo</a>
                    </div>
                </div>
            </div>
          </div>
          <div class="chart tab-pane" id="area2">
            <?php 

                echo $form->showInput("cliente_cnpj", $this, array("col-width" => 2)); 
                echo $form->showInput("cliente_email", $this, array("col-width" => 4));
                echo $form->showInput("cliente_sigla", $this, array("col-width" => 2)); 
                echo $form->showInput("cliente_razao_social", $this, array("col-width" => 4)); 
                echo $form->showInput("cliente_nome_fantasia", $this, array("col-width" => 4)); 
                //echo $form->showFile("cliente_logo", $this, array("col-width" => 4)); 
                $input = $form->get("cliente_id_arquivo_logo"); echo $input->render($this); 
            ?>
            <div class="form-group">
            <label class="col-sm-2 control-label" for=""></label>            
                <div class="controls">
                    <div class="col-sm-2">
                        <a class="btn btn-primary" href="#area3" data-toggle="tab" aria-expanded="false"><i class="fa fa-arrow-circle-o-right"></i> Proximo</a>
                    </div>
                </div>
            </div>
          </div>
          <div class="chart tab-pane" id="area3">
            <?php 
                echo $form->showInput("smtp_email", $this, array("col-width" => 4)); 
                echo $form->showInput("smtp_host", $this, array("col-width" => 3)); 
                echo $form->showInput("smtp_port", $this, array("col-width" => 1)); 
                echo $form->showInput("smtp_username", $this, array("col-width" => 2)); 
                echo $form->showInput("smtp_password", $this, array("col-width" => 2)); 
                echo $form->show("Select", "smtp_secure", $this, array("col-width" => 2)); 
            ?>
            <div class="form-group">
            <label class="col-sm-2 control-label" for=""></label>            
                <div class="controls">
                    <div class="col-sm-2">
                        <?php
                            $input = $form->get("submit");   
                            echo $this->formInput($input); 
                        ?>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>
    </div>
<?php
echo $this->form()->closeTag();