<?php 
$sm = $this->getHelperPluginManager()->getServiceLocator();
$app = $sm->get("AplicacaoFachada");

$result = $app->getRegiaoAtual(array());
if (isset($result["data"]) && $result["data"]) {
    $regiao_atual = $result["data"];
    $txt_regiao_atual = "--";
    if (isset($regiao_atual["tostring"])) {
        $txt_regiao_atual = $regiao_atual["tostring"];
    }
?>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Região Atual</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <dl class="dl-horizontal">
            <dt>Região Atual:</dt>
            <dd><?php echo $txt_regiao_atual; ?></dd>
        </dl>
    </div>
</div>
<?php }