<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$app = $sm->get("AplicacaoFachada");

$campos = $dts = array();
if (isset($this->campos)) {
    $campos = $this->campos;
}
$filtros = $dts = array();
if (isset($this->filtros)) {
    $filtros = $this->filtros;
}
if (isset($this->dts)) {
    $dts = $this->dts;
}
?>
<script type="text/javascript">
    $(document).ready(function () {
        $("#id_dt").change(function () {
            $("#bt_submit").click();
        });
        $("#bt_limpar").click(function () {
            $("#id_dt").val("");
            $("#bt_submit").click();
        });
        $("#pesquisa_btn_limpar").click(function() {
            $(".pesquisa_field").val("");
            $("#pesquisa_form").submit();
        });
        
        var show_pesquisa_field = false;
        var ctrls = $(".pesquisa_field");
        if (ctrls.length) {
            $.each(ctrls, function(idc, obj) {
                if ($(obj).val().length) {
                    show_pesquisa_field = true;
                    return true;
                }
            });
        }
        if (show_pesquisa_field) {
            $("#pesquisa_form").show();
        }
    });
</script>
<div class="row">
    <form action="<?php echo $this->url(null, array("controller" => "documento", "action" => "index")); ?>" method="POST" name="formulario_doc_tipo" class="form-horizontal" id="formulario_doc_tipo">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Selecione o Tipo de Documento</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group descricao_row">
                        <label class="col-sm-2 control-label" for="id_dt">Tipo de Documento:</label>            
                        <div class="controls row_descricao">
                            <div class="col-sm-4">
                                <select name="id_dt" id="id_dt" class="form-control">
                                    <option value=""<?php echo (!$this->id_dt) ? "selected" : ""; ?>>==> SELECIONE <==</option>
                                    <?php foreach ($dts as $dt) { ?>
                                        <option value="<?php echo $dt["id"]; ?>" <?php echo ($this->id_dt == $dt["id"]) ? "selected" : ""; ?>><?php echo $dt["tostring"]; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label"></label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="submit" name="submit" class="btn btn-primary" value="Carregar Documentos" id="bt_submit">
                                <input type="button" value="Limpar" id="bt_limpar" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <?php if ($this->id_dt) { ?>
    <form action="" method="post" class="form-horizontal" id="pesquisa_form" style="display:none;">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Formulário de Pesquisa</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            <label for="pesquisa_usuario_nome" class="col-sm-2 control-label">Usuário Criador: </label>
                            <div class="controls">
                                <div class="col-sm-4">
                                    <input type="text" name="pesquisa_usuario_nome" id="pesquisa_usuario_nome" class="pesquisa_field form-control" value="<?php echo $this->pesquisa_dados["pesquisa_usuario_nome"]; ?>" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pesquisa_data_criacao_inicio" class="col-sm-2 control-label">Data Criação - Início: </label>
                            <div class="controls">
                                <div class="col-sm-2">
                                    <input type="text" name="pesquisa_data_criacao_inicio" id="pesquisa_data_criacao_inicio" class="pesquisa_field form-control form-control-item mask_data" value="<?php echo $this->pesquisa_dados["pesquisa_data_criacao_inicio"]; ?>" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pesquisa_data_criacao_final" class="col-sm-2 control-label">Data Criação - Final: </label>
                            <div class="controls">
                                <div class="col-sm-2">
                                    <input type="text" name="pesquisa_data_criacao_final" id="pesquisa_data_criacao_final" class="pesquisa_field form-control form-control-item mask_data" value="<?php echo $this->pesquisa_dados["pesquisa_data_criacao_final"]; ?>" />
                                </div>
                            </div>
                        </div>
                        <?php
                        if (count($filtros)) {
                            foreach ($filtros as $campo) {
                                $id_dc = 0;
                                if (isset($campo["id"])) {
                                    $id_dc = $campo["id"];
                                }
                                if ($id_dc) {
                                    $name = "filtro_" . $campo["nome"];
                                    $value = "";
                                    if (isset($this->pesquisa_dados[$name])) {
                                        $value = $this->pesquisa_dados[$name];
                                    }
                                    $result = $app->getDocumentoCampoControle(array("id_documento_campo" => $id_dc, "prefixo" => "filtro_", "documento_campo_value" => $value, "class" => "pesquisa_field"));
                                    if (isset($result["data"]["html"]) && !empty($result["data"]["html"])) {
                                        echo $result["data"]["html"];
                                    }
                                }
                            }
                        }
                        ?>
                        <div class="form-group">
                            <label for="descricao" class="col-sm-2 control-label"></label>
                            <div class="controls">
                                <div class="col-sm-4">
                                    <input type="submit" value="Procurar" class="btn btn-primary" />
                                    <input type="button" value="Limpar" class="btn btn-default" id="pesquisa_btn_limpar" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr class="titulo">
                                <th width="60px">ID</th>
                                <th>Tipo</th>
                                <th>Criador</th>
                                <th>Data / Hora</th>
                                <?php
                                foreach ($campos as $campo) {
                                    ?>
                                    <th><?php echo $campo["tostring"]; ?></th>
                                    <?php
                                }
                                ?>
                                <th class="btn_titulo"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (isset($this->result["registros"]) && !empty($this->result["registros"])) { ?>
                                <?php
                                foreach ($this->result["registros"] as $registro) {
                                    $txt_id = $txt_tipo = $txt_data_hora = $txt_usuario = "--";
                                    if (isset($registro["id"]) && $registro["id"]) {
                                        $txt_id = $registro["id"];
                                        $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
                                    }
                                    
                                    if (isset($registro["documento_tipo"]["tostring"]) && $registro["documento_tipo"]["tostring"]) {
                                        $txt_tipo = $registro["documento_tipo"]["tostring"];
                                    }
                                    
                                    if (isset($registro["documento_tipo"]["tostring"]) && $registro["documento_tipo"]["tostring"]) {
                                        $txt_tipo = $registro["documento_tipo"]["tostring"];
                                    }
                                    if (isset($registro["data_criacao"]) && $registro["data_criacao"]) {
                                        $txt_data_hora = Marabaixo\Util::formatData($registro["data_criacao"]);
                                        if (isset($registro["hora_criacao"]) && $registro["hora_criacao"]) {
                                            $txt_data_hora .= " - " . $registro["hora_criacao"];
                                        }
                                    }
                                    if (isset($registro["usuario"]["pessoa_fisica"]["nome"])) {
                                        $nome = $registro["usuario"]["pessoa_fisica"]["nome"];
                                        if ($nome) {
                                            $txt_usuario = $nome;
                                        }
                                    }
                                    ?>
                                    <tr>
                                        <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                                        <td><a href="<?php echo $url_view; ?>"><?php echo $txt_tipo; ?></a></td>
                                        <td><a href="<?php echo $url_view; ?>"><?php echo $txt_usuario; ?></a></td>
                                        <td><a href="<?php echo $url_view; ?>"><?php echo $txt_data_hora; ?></a></td>
                                        <?php
                                        foreach ($campos as $campo) {
                                            $txt = "--";
                                            if (!(isset($campo["nome"]) && $campo["nome"])) {
                                                continue;
                                            }
                                            
                                            $nome = $campo["nome"];
                                            if (isset($registro["valores"][$nome]) && $registro["valores"][$nome]) {
                                                $txt = $registro["valores"][$nome];
                                            }
                                            ?>
                                            <td><a href="<?php echo $url_view; ?>"><?php echo $txt; ?></a></td>
                                            <?php
                                        }
                                        ?>

                                        <td>
                                            <div class="btn-group pull-right">
                                                <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                                                <a class="btn btn-default" title="Editar" href="<?php echo $this->url(null, array("action" => "editar", "id" => $txt_id), true); ?>"><i class="fa fa-cogs"></i></a>
                                                <a class="btn btn-default link_confirma" title="Excluir" href="<?php echo $this->url(null, array("action" => "excluir", "id" => $txt_id), true); ?>"><i class="fa fa-trash-o"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php } ?>
    <?php } else { ?>
                                <tr>
                                    <td colspan="<?php echo (4 + count($campos)); ?>)"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
                                </tr>
    <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
    <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
                </div>
            </div>
<?php } ?>
    </div>
</div>