<?php
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
    $("#cpf").focus();
    $("#cpf").inputmask("999.999.999-99");
});
<?php
$this->inlineScript()->captureEnd();

$form = $this->form;
$form->setAttribute('action', $this->url(null, array("controller" => "auth", "action" => "novoadmin")));
$form->setAttribute('class', "form-horizontal");

$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="col-lg-12 well">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Cadastrar Primeiro Administrador</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
<?php 
    echo $form->showInput("cpf", $this, array("col-width" => 2)); 
    echo $form->showInput("nome", $this, array("col-width" => 4)); 
    echo $form->showInput("email", $this, array("col-width" => 4)); 
    echo $form->showInput("data_nascimento", $this, array("col-width" => 2)); 
?>
        <br />
<?php
    echo $form->showInput("senha", $this, array("col-width" => 2)); 
    echo $form->showInput("confirma_senha", $this, array("col-width" => 2)); 
?>
            </div>
        </div>
    </div>
    <div class="col-lg-12 well">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Configurações do Sistema</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
<?php 
echo $form->showInput("sistema_sigla", $this, array("col-width" => 2)); 
echo $form->showInput("sistema_nome", $this, array("col-width" => 4)); 
echo $form->showFile("sistema_logo", $this, array("col-width" => 4)); 
?>
        <legend>Cliente</legend>
        <br />
<?php 
echo $form->showInput("cliente_cnpj", $this, array("col-width" => 2)); 
echo $form->showInput("cliente_email", $this, array("col-width" => 4));
echo $form->showInput("cliente_sigla", $this, array("col-width" => 2)); 
echo $form->showInput("cliente_razao_social", $this, array("col-width" => 4)); 
echo $form->showInput("cliente_nome_fantasia", $this, array("col-width" => 4)); 
echo $form->showFile("cliente_logo", $this, array("col-width" => 4)); 
?>
<div class="form-group">
    <label for="" class="col-sm-2 control-label"></label>
    <div class="controls">
        <div class="col-sm-4">
<?php
$input = $form->get("submit");   
echo $this->formInput($input); 
?>
        </div>
    </div>
</div>
            </div>
        </div>

        
    </div>
<?php
echo $this->form()->closeTag();