<?php
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
    $("#email").focus();
});
<?php
$this->inlineScript()->captureEnd();

$form = $this->form;
$form->setAttribute('action', $this->url(null, array("action" => "recupera"), true));
$form->setAttribute('class', "form-horizontal");

$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="col-lg-12 well-lg">
<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Informe seu E-mail para Recuperação de Senha</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
    <?php
        echo $form->showInput("email", $this, array("col-width" => 4)); 
    ?>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"></label>
        <div class="controls">
            <div class="col-sm-4">
                <?php
                $input = $form->get("submit");   
                echo $this->formInput($input); 
                ?>
                <a href="<?php echo $this->url(null, array("controller" => "auth", "action" => "index")); ?>" class="btn btn-default">Cancelar</a>
            </div>
        </div>
    </div>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
    </div>
</div>
    </div>
<?php
echo $this->form()->closeTag();