<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array(), true));
$form->setAttribute('class', "form-horizontal");

$form->prepare();
?>
<script>
    $(function(){
        $("#data_inicio").datepicker({dateFormat: 'dd/mm/yy',separator: ' ',minDate: new Date()});
        $("#data_fim").datepicker({dateFormat: 'dd/mm/yy',separator: ' ',minDate: new Date()});       
    });
</script>
<div class="row">
    <div class="col-md-12">
        <?php
        echo $this->form()->openTag($form);
        ?>
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Receber Servidor</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <?php
                $input = $form->get("id_servidor"); 
                echo $this->formInput($input);
                echo $form->showInput("servidor", $this, array("col-width" => 4));
                echo $form->showInput("matricula", $this, array("col-width" => 2));                
                echo $form->showInput("cargo", $this, array("col-width" => 2));                
                echo $form->showInput("data_inicio", $this, array("col-width" => 2));                
                echo $form->showInput("data_fim", $this, array("col-width" => 2));                
                $input = $form->get("encaminhamento_status");
                echo $this->formInput($input);
                $input = $form->get("id_orgao"); echo $input->render($this);                
                $input = $form->get("id_lotacao_tipo"); echo $input->render($this); 
                
                echo $this->formLabel($form->get('chefia'));
                echo $this->formElement($form->get('chefia'));
                
                
                
                ?>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label"></label>
                    <div class="controls">
                        <div class="col-sm-4">
                            <?php
                            $input = $form->get("submit");
                            echo $this->formInput($input);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>