<div class="row">
<form action="" method="post" class="form-horizontal" id="pesquisa_form">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Formulário de Pesquisa</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="form-group">
                    <label for="pesquisa_descricao" class="col-sm-2 control-label">Nome do Município: </label>
                    <div class="controls">
                        <div class="col-sm-4">
                            <input type="text" name="filtro_descricao" id="filtro_descricao" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_descricao"]; ?>" />
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="descricao" class="col-sm-2 control-label"></label>
                    <div class="controls">
                        <div class="col-sm-4">
                            <input type="submit" value="Procurar" class="btn btn-primary" />
                            <input type="button" value="Limpar" class="btn btn-default" id="pesquisa_btn_limpar" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
    
    <div class="col-md-12">
<div class="box">
    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="titulo">
                        <th width="60px">ID</th>
                        <th>Uf</th>
                        <th>Descrição</th>
                        <th>IBGE</th>
                        <th class="btn_titulo"></th>
                    </tr>
                </thead>
                <tbody>
    <?php if (isset($this->result["registros"]) && !empty($this->result["registros"])) { ?>
    <?php 
    foreach ($this->result["registros"] as $registro) {
        $txt_id = $txt_codigo = $txt_descricao = $txt_ibge = "--";

        if (isset($registro["id"]) && $registro["id"]) {
            $txt_id = $registro["id"]; 
            $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
        }
        if (isset($registro["descricao"]) && $registro["descricao"]) { $txt_descricao = $registro["descricao"]; }
        if (isset($registro["uf"]["codigo"]) && $registro["uf"]["codigo"]) { $txt_codigo = $registro["uf"]["codigo"]; }
        if (isset($registro["ibge"]) && $registro["ibge"]) { $txt_ibge = $registro["ibge"]; }
    ?>
                <tr>
                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_codigo; ?></a></td>
                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_descricao; ?></a></td>
                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_ibge; ?></a></td>
                    <td>
                        <div class="btn-group pull-right">
                            <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                            <a class="btn btn-default" title="Editar" href="<?php echo $this->url(null, array("action" => "editar", "id" => $txt_id), true); ?>"><i class="fa fa-cogs"></i></a>                        
                            <a class="btn btn-default link_confirma" title="Excluir" href="<?php echo $this->url(null, array("action" => "excluir", "id" => $txt_id), true); ?>"><i class="fa fa-trash-o"></i></a>
                            <a class="btn btn-default" title="Bairro" href="<?php echo $this->url(null, array("action" => "bairro", "id" => $txt_id), true); ?>"><i class="fa fa-list-ul"></i></a>
                        </div>
                    </td>
                </tr>
    <?php } ?>
    <?php } else { ?>
                <tr>
                    <td colspan="7"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
                </tr>
    <?php } ?>
                </tbody>
            </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
        <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
    </div>
</div>
        </div>
    
    </div>
</div>