<?php
$txt_id = $txt_codigo = $txt_descricao = $txt_ibge = "--";
if (isset($this->result)) {
    $registro = $this->result;
    
    if (isset($registro["id"]) && $registro["id"]) {
        $txt_id = $registro["id"]; 
        $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
    }
    if (isset($registro["descricao"]) && $registro["descricao"]) { $txt_descricao = $registro["descricao"]; }
    if (isset($registro["uf"]["codigo"]) && $registro["uf"]["codigo"]) { $txt_codigo = $registro["uf"]["codigo"]; }
    if (isset($registro["ibge"]) && $registro["ibge"]) { $txt_ibge = $registro["ibge"]; }
}
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Visualizar Municipio</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>Uf: </dt>
                    <dd><?php echo $txt_codigo; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição: </dt>
                    <dd><?php echo $txt_descricao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>IBGE: </dt>
                    <dd><?php echo $txt_ibge; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>