<div class="row">
    <form action="" method="post" class="form-horizontal" id="pesquisa_form" style="display:none">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h4>Formulário de Pesquisa</h4>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <label for="filtro_id_log_tipo" class="col-sm-2 control-label">Tipo de Log: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <select name="filtro_id_log_tipo" id="filtro_id_log_tipo" class="form-control pesquisa_field">
                                    <option value="" <?php echo (!$this->pesquisa_dados["filtro_id_log_tipo"]) ? "selected" : ""; ?>>==> SELECIONE <==</option>
                                    <?php foreach ($this->log_tipos as $lt) { ?>
                                        <option value="<?php echo $lt["id"]; ?>" <?php echo ($this->pesquisa_dados["filtro_id_log_tipo"] == $lt["id"]) ? "selected" : ""; ?>><?php echo $lt["tostring"]; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_data_inicial" class="col-sm-2 control-label">Data Inicial: </label>
                        <div class="controls">
                            <div class="col-sm-2">
                                <input type="text" name="filtro_data_inicial" id="filtro_data_inicial" class="form-control pesquisa_field mask_data" value="<?php echo $this->pesquisa_dados["filtro_data_inicial"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_data_final" class="col-sm-2 control-label">Data Final: </label>
                        <div class="controls">
                            <div class="col-sm-2">
                                <input type="text" name="filtro_data_final" id="filtro_data_final" class="form-control pesquisa_field mask_data" value="<?php echo $this->pesquisa_dados["filtro_data_final"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_cpf" class="col-sm-2 control-label">C.P.F.: </label>
                        <div class="controls">
                            <div class="col-sm-2">
                                <input type="text" name="filtro_cpf" id="filtro_cpf" class="form-control pesquisa_field mask_cpf" value="<?php echo $this->pesquisa_dados["filtro_cpf"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_nome" class="col-sm-2 control-label">Nome: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="text" name="filtro_nome" id="filtro_nome" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_nome"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_email" class="col-sm-2 control-label">E-mail: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="text" name="filtro_email" id="filtro_email" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_email"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_id_log_bd_tipo" class="col-sm-2 control-label">Tipo de Log de Banco: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <select name="filtro_id_log_bd_tipo" id="filtro_id_log_bd_tipo" class="form-control pesquisa_field">
                                    <option value="" <?php echo (!$this->pesquisa_dados["filtro_id_log_bd_tipo"]) ? "selected" : ""; ?>>==> SELECIONE <==</option>
                                    <?php foreach ($this->log_bd_tipos as $lt) { ?>
                                        <option value="<?php echo $lt["id"]; ?>" <?php echo ($this->pesquisa_dados["filtro_id_log_bd_tipo"] == $lt["id"]) ? "selected" : ""; ?>><?php echo $lt["tostring"]; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_schema" class="col-sm-2 control-label">Schema: </label>
                        <div class="controls">
                            <div class="col-sm-3">
                                <input type="text" name="filtro_schema" id="filtro_schema" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_schema"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_tabela" class="col-sm-2 control-label">Tabela: </label>
                        <div class="controls">
                            <div class="col-sm-3">
                                <input type="text" name="filtro_tabela" id="filtro_tabela" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_tabela"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_identificador" class="col-sm-2 control-label">ID do Registro: </label>
                        <div class="controls">
                            <div class="col-sm-2">
                                <input type="text" name="filtro_identificador" id="filtro_identificador" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_identificador"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="descricao" class="col-sm-2 control-label"></label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="submit" value="Procurar" class="btn btn-primary" />
                                <input type="button" value="Limpar" class="btn btn-default" id="pesquisa_btn_limpar" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
            </div>
            <div class="box-body">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr class="titulo">
                            <th width="60px">ID</th>
                            <th>Tipo</th>
                            <th>Data e Hora</th>
                            <th>Endereço IP</th>
                            <th>Usuário / E-Mail</th>
                            <th>Componente</th>
                            <th>Controller</th>
                            <th>Action</th>
                            <th class="btn_titulo"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (isset($this->result["registros"])) { ?>
                            <?php
                            foreach ($this->result["registros"] as $registro) {
                                $txt_id = $txt_tipo = $txt_data_hora = $txt_ip = $txt_usuario = $txt_componente = $txt_controller = $txt_action = "--";
                                if (isset($registro["id"]) && $registro["id"]) {
                                    $txt_id = $registro["id"];
                                    $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
                                }
                                if (isset($registro["log_tipo"]["tostring"]) && $registro["log_tipo"]["tostring"]) {
                                    $txt_tipo = $registro["log_tipo"]["tostring"];
                                }
                                if (isset($registro["log_data"]) && $registro["log_data"]) {
                                    $txt = array();
                                    $txt[] = Marabaixo\Util::formatData($registro["log_data"]);
                                    if (isset($registro["log_hora"]) && $registro["log_hora"]) {
                                        $txt[] = $registro["log_hora"];
                                    }
                                    $txt_data_hora = implode(" ", $txt);
                                }
                                if (isset($registro["ip"]) && $registro["ip"]) {
                                    $txt_ip = $registro["ip"];
                                }
                                if (isset($registro["usuario"]["tostring"]) && !empty($registro["usuario"]["tostring"])) {
                                    $txt_usuario = $registro["usuario"]["tostring"];
                                } elseif (isset($registro["email"]) && !empty($registro["email"])) {
                                    $txt_usuario = $registro["email"];
                                }
                                if (isset($registro["componente"]["tostring"]) && !empty($registro["componente"]["tostring"])) {
                                    $txt_componente = $registro["componente"]["tostring"];
                                }
                                if (isset($registro["controller_obj"]["tostring"]) && !empty($registro["controller_obj"]["tostring"])) {
                                    $txt_controller = $registro["controller_obj"]["tostring"];
                                } elseif (isset($registro["controller"]) && !empty($registro["controller"])) {
                                    $txt_controller = $registro["controller"];
                                }
                                if (isset($registro["action_obj"]["tostring"]) && !empty($registro["action_obj"]["tostring"])) {
                                    $txt_action = $registro["action_obj"]["tostring"];
                                } elseif (isset($registro["action"]) && !empty($registro["action"])) {
                                    $txt_action = $registro["action"];
                                }
                                ?>
                                <tr>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_tipo; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_data_hora; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_ip; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_usuario; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_componente; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_controller; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_action; ?></a></td>
                                    <td>
                                        <div class="btn-group pull-right">
                                            <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="9"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="box-footer clearfix">
                <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
            </div>
        </div>

    </div>
</div>