<script type="text/javascript">
    function importar() {
        $("#importar_form").toggle();
    }
</script>
<div class="row">
    <form action="<?php echo $this->url(null, array("action" => "importar"), true); ?>" enctype="multipart/form-data" method="post" class="form-horizontal" id="importar_form" style="display:none;">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Importar</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <label for="importar_arquivo" class="col-sm-2 control-label">Arquivo: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="file" name="importar_arquivo" id="importar_arquivo" class="form-control pesquisa_field" value="" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="descricao" class="col-sm-2 control-label"></label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="submit" value="Importar" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr class="titulo">
                            <th width="60px">ID</th>
                            <th>Chave</th>
                            <th>Descrição</th>
                            <th class="btn_titulo"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (isset($this->result["registros"]) && !empty($this->result["registros"])) { ?>
                            <?php
                            foreach ($this->result["registros"] as $registro) {
                                $txt_id = $txt_chave = $txt_descricao = "--";
                                if (isset($registro["id"]) && $registro["id"]) {
                                    $txt_id = $registro["id"];
                                    $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
                                }
                                if (isset($registro["tostring"]) && $registro["tostring"]) {
                                    $txt_descricao = $registro["tostring"];
                                }
                                if (isset($registro["chave"]) && $registro["chave"]) {
                                    $txt_chave = $registro["chave"];
                                }
                                ?>
                                <tr>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_chave; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php echo $txt_descricao; ?></a></td>
                                    <td>
                                        <div class="btn-group pull-right">
                                            <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                                            <a class="btn btn-default" title="Editar" href="<?php echo $this->url(null, array("action" => "editar", "id" => $txt_id), true); ?>"><i class="fa fa-cogs"></i></a>
                                            <a class="btn btn-default link_confirma" title="Excluir" href="<?php echo $this->url(null, array("action" => "excluir", "id" => $txt_id), true); ?>"><i class="fa fa-trash-o"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="6"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div><!-- /.box-body -->
            <div class="box-footer clearfix">
                <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
            </div>
        </div>

    </div>
</div>