<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Dados Pessoais') ?></h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table pull-right">
            <tr>
                <td rowspan="3"><img class="img-thumbnail"  src="<?php echo $this->basePath(); ?>/img/usuario.png" style="width: 70px; height: 70px;"></td>
                <td><strong>Nome:</strong></td>
                <td>Francivan dos Santos de Castro</td>
            </tr>  
            <tr>
                <td><strong>Email:</strong></td>
                <td>francivan.castro@gemail.com</td>
            </tr>
            <tr>
                <td><strong>Telefone:</strong></td>
                <td>(96) 9152 -0329</td>
            </tr>
            </table>
         </div>
    </div>
</div>