<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array(), true));
$form->setAttribute('class', "form-horizontal");

$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-md-12">
        <?php include("include/regiao.phtml"); ?>    

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Cadastro de Estabelecimento de Saúde</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <?php
                $input = $form->get("id");
                echo $this->formInput($input);
                echo $form->showInput("codigo_cnes", $this, array("col-width" => 2));
                $input = $form->get("id_estabelecimento_saude_tipo");
                echo $input->render($this);
                $input = $form->get("id_estabelecimento_gestao");
                echo $input->render($this);
                echo $form->showInput("sigla", $this, array("col-width" => 2));
                echo $form->showInput("descricao", $this, array("col-width" => 4));
                $input = $form->get("id_pessoa_fisica");
                echo $input->render($this);
                $input = $form->get("id_pessoa_juridica");
                echo $input->render($this);
                ?>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Endereço</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <?php echo $this->endereco; ?>        
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label"></label>
                    <div class="controls">
                        <div class="col-sm-4">
                            <?php
                            $input = $form->get("submit");
                            echo $this->formInput($input);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->form()->closeTag();
