<div class="row">
<div class="col-md-12">
        <?php include("include/regiao.phtml"); ?>
<div class="box">
    <div class="box-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr class="titulo">
                    <th width="60px">ID</th>
                    <th>Codigo CNES</th>
                    <th>Tipo</th>
                    <th>Gestão</th>
                    <th>Sigla</th>
                    <th>Descrição</th>
                    <th>Responsável</th>
                    <th class="btn_titulo"></th>
                </tr>
            </thead>
            <tbody>
<?php if (isset($this->result["registros"]) && !empty($this->result["registros"])) { ?>
<?php 
foreach ($this->result["registros"] as $registro) { 
    $txt_id = $txt_sigla = $txt_descricao = $txt_responsavel = $txt_codigo_cnes = $txt_tipo = $txt_gestao = "--";
    if (isset($registro["id"]) && $registro["id"]) {
        $txt_id = $registro["id"]; 
        $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
    }
    if (isset($registro["tostring"]) && $registro["tostring"]) { $txt_descricao = $registro["tostring"]; }
    if (isset($registro["sigla"]) && $registro["sigla"]) { $txt_sigla = $registro["sigla"]; }
    if (isset($registro["codigo_cnes"]) && $registro["codigo_cnes"]) { $txt_codigo_cnes = $registro["codigo_cnes"]; }
    if (isset($registro["estabelecimento_saude_tipo"]["descricao"]) && $registro["estabelecimento_saude_tipo"]["descricao"]) { $txt_tipo = $registro["estabelecimento_saude_tipo"]["descricao"]; }
    if (isset($registro["estabelecimento_gestao"]["descricao"]) && $registro["estabelecimento_gestao"]["descricao"]) { $txt_gestao = $registro["estabelecimento_gestao"]["descricao"]; }
    if (isset($registro["usuario"]["pessoa_fisica"]["id"]) && $registro["usuario"]["pessoa_fisica"]["id"]) { $txt_responsavel = $registro["usuario"]["pessoa_fisica"]["tostring"]; }
   
    
?>
            <tr>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_codigo_cnes; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_tipo; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_gestao; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_sigla; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_descricao; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_responsavel; ?></a></td>
                <td>
                    <div class="btn-group pull-right">
                        <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                        <a class="btn btn-default" title="Editar" href="<?php echo $this->url(null, array("action" => "editar", "id" => $txt_id), true); ?>"><i class="fa fa-cogs"></i></a>
                        <a class="btn btn-default link_confirma" title="Excluir" href="<?php echo $this->url(null, array("action" => "excluir", "id" => $txt_id), true); ?>"><i class="fa fa-trash-o"></i></a>
                    </div>
                </td>
            </tr>
<?php } ?>
<?php } else { ?>
            <tr>
                <td colspan="8"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
            </tr>
<?php } ?>
            </tbody>
        </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
        <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
    </div>
</div>

</div>
</div>