<?php
$txt_id = $txt_descricao = $txt_action = $txt_controller = "--";
if (isset($this->result["id"])) { $txt_id = $this->result["id"]; }
if (isset($this->result["descricao"])) { $txt_descricao = $this->result["descricao"]; }
if (isset($this->result["action"])) { $txt_action = $this->result["action"]; }
if (isset($this->result["controller"]["tostring"])) { $txt_controller = $this->result["controller"]["tostring"]; }
?>
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Visualizar Action</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <dl class="dl-horizontal">
            <dt>Controller: </dt>
            <dd><?php echo $txt_controller; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>ID: </dt>
            <dd><?php echo $txt_id; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Descrição: </dt>
            <dd><?php echo $txt_descricao; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Action: </dt>
            <dd><?php echo $txt_action; ?></dd>
        </dl>
        </div><!-- /.box-body -->
        <div class="box-footer clearfix">
        </div>
    </div>
</div>
</div>