
<form action="" method="post" class="form-horizontal" id="pesquisa_form">
    <div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Formulário de Pesquisa</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="form-group">
            <label class="col-sm-2 control-label">Data de inscrição: </label>
            <div class="controls">
                <div class="col-sm-4">
                   <div class="input-daterange input-group" id="datepicker">
                    <input type="text" name="data" class="form-control mask_data datepicker" value="" />
                    <span class="input-group-addon">A</span>
                    <input type="text" name="data2" class="form-control mask_data datepicker" value="" />
                </div> 
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Número de CRC: </label>
            <div class="controls">
                <div class="col-sm-4">
                    <input type="text" name="crc" class="form-control" value="" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">CPF/CNPJ do Fornecedor: </label>
            <div class="controls">
                <div class="col-sm-4">
                    <input type="text" name="cpf" class="form-control" value="" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Nome Empresarial/Nome do Fornecedor: </label>
            <div class="controls">
                <div class="col-sm-4">
                    <input type="text" name="empre" class="form-control" value="" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Linhas de fornecimento: </label>
            <div class="controls">
                <div class="col-sm-4">
                    <input type="text" name="cpf" class="form-control" value="" />
                </div>
            </div>
        </div>
            <div class="form-group">
                <label for="descricao" class="col-sm-2 control-label"></label>
                <div class="controls">
                    <div class="col-sm-4">
                        <input type="submit" value="Procurar" class="btn btn-primary" />
                        <input type="button" value="Limpar" class="btn btn-default" id="pesquisa_btn_limpar" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


<div class="box">
    <div class="box-body">
        <table class="table table-hover">
                <thead>
                    <tr>
                      <th>ID</th>
                      <th>Nome</th>
                      <th>Data</th>
                      <th>Status</th>
                      <th><span class="pull-right">Ferramentas</span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td>183</td>
                      <td>José Luis</td>
                      <td>11/07/2014</td>
                      <td><span class="label label-success">Approved</span></td>
                      <td>
                        
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                        
                      </td>
                    </tr>
                    <tr>
                      <td>219</td>
                      <td>Alexander Pierce</td>
                      <td>11/07/2014</td>
                      <td><span class="label label-warning">Pending</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>657</td>
                      <td>Bob Doe</td>
                      <td>11/07/2014</td>
                      <td><span class="label label-primary">Approved</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>175</td>
                      <td>Mike Doe</td>
                      <td>11/07/2014</td>
                      <td><span class="label label-danger">Denied</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                </tbody>
        </table>
    </div>
    <div class="box-footer clearfix">
        
    </div>
</div>