<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
$(".form-control").first().focus().select();
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array(), true));
$form->setAttribute('class', "form-horizontal");

$form->prepare();
?>
<script>
    $(function () {
        $("#data_ingresso").datepicker({dateFormat: 'dd/mm/yy', separator: ' ', minDate: new Date()});
        $("#data_ultima_alteracao").datepicker({dateFormat: 'dd/mm/yy', separator: ' ', minDate: new Date()});
    });
</script>

<div class="row mt">
    <div class="col-md-12">
        <?php
        echo $this->form()->openTag($form);
        ?>
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Cadastro Orgão</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <?php
                $input = $form->get("id");

                echo $this->formInput($input);
                echo $form->showInput("codigo", $this, array("col-width" => 4));
                echo $form->showInput("descricao", $this, array("col-width" => 4));
                echo $form->showInput("portaria", $this, array("col-width" => 4));
                $input = $form->get("id_orgao_superior");
                echo $input->render($this);
                ?>
                <div class="check" id="gestao_ingresso">
                    <?php
                    echo $this->formLabel($form->get('gestao_ingresso'));
                    echo $this->formElement($form->get('gestao_ingresso'));
                    ?>
                </div>
                <?php
                $resultados = $this->resultgi['data'];
             
                if (count($resultados) == 0) {
                    ?>
                </div>
            </div>

            <?php ?>

            <div class="box" id="servidor">
                <div class="box-header with-border">
                    <h3 class="box-title">Ingresso de Servidor</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?php
                    $input = $form->get("id");
                    $input = $form->get("id_pessoa_fisica");
                    echo $input->render($this);
                    echo $form->showInput("matricula", $this, array("col-width" => 2));
                    echo $form->showInput("identificacao_unica", $this, array("col-width" => 2));
                    echo $form->showInput("data_ingresso", $this, array("col-width" => 2));
                    echo $form->showInput("data_ultima_alteracao", $this, array("col-width" => 2));
                    echo $form->showInput("carga_horaria", $this, array("col-width" => 2));
                    $input = $form->get("id_servidor_cargo");
                    echo $input->render($this);
                    $input = $form->get("id_servidor_classe");
                    echo $input->render($this);
                    $input = $form->get("id_servidor_funcao");
                    echo $input->render($this);
                    $input = $form->get("id_servidor_nivel");
                    echo $input->render($this);
                    $input = $form->get("id_regime_juridico");
                    echo $input->render($this);
                    ?>

                </div>
            </div>
        <?php } else { ?>
            <script type="text/javascript">
                $(function () {
                    $('#gestao_ingresso').hide();
                })
            </script>

        <?php } ?>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label"></label>
            <div class="controls">
                <div class="col-sm-4">
                    <?php
                    $input = $form->get("submit");
                    echo $this->formInput($input);
                    ?>
                </div>
            </div>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
