<?php 
$info_system = $sistema = $usuario = $sistema_arquivo_logo = false;
$sm = $this->getHelperPluginManager()->getServiceLocator();
$app = $sm->get("AplicacaoFachada");
if ($app) {
    $xml = $app->getInfoSistema();
    $info_system = \Marabaixo\Util::xml_to_array($xml);
    if (isset($info_system["data"]["config"]["sistema"])) {
        $sistema = $info_system["data"]["config"]["sistema"];
        if (isset($sistema["id_arquivo_logo"]) && $sistema["id_arquivo_logo"]) {
            $xml = $app->getInfoArquivo(\Marabaixo\Util::array_to_xml(array("id" => $sistema["id_arquivo_logo"])));
            $sistema_arquivo_logo = \Marabaixo\Util::xml_to_array($xml);
            if (isset($sistema_arquivo_logo["data"])) {
                $sistema_arquivo_logo = $sistema_arquivo_logo["data"];
            }
        }
    }
    $xml = $app->pegaUsuarioLogado();
    $array = \Marabaixo\Util::xml_to_array($xml);
    if (isset($array["data"]["usuario"])) {
        $usuario = $array["data"]["usuario"];
    }
}
?>
<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(".:: {$sistema["nome"]} ::.")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                        
                        ->prependStylesheet($this->basePath() . '/css/skins/_all-skins.min.css')
                        ->prependStylesheet($this->basePath() . '/plugins/jquery_ui/jquery-ui.min.css')
                        ->prependStylesheet($this->basePath() . '/css/AdminLTE.min.css')
                        ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                
            ->prependFile($this->basePath() . '/js/marabaixo.js') 
            ->prependFile($this->basePath() . '/plugins/file_upload/js/jquery.fileupload.js')
            ->prependFile($this->basePath() . '/js/app.min.js')
            
            ->prependFile($this->basePath() . '/plugins/slimScroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath() . '/plugins/sparkline/jquery.sparkline.min.js')
            ->prependFile($this->basePath() . '/plugins/knob/jquery.knob.js')
            ->prependFile("https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js")
            ->prependFile($this->basePath() . '/plugins/morris/morris.min.js')
            ->prependFile($this->basePath() . '/plugins/chartjs/Chart.min.js')
            ->prependFile($this->basePath() . '/plugins/sparkline/jquery.sparkline.min.js')
            ->prependFile($this->basePath() . '/plugins/fastclick/fastclick.min.js')
            ->prependFile($this->basePath() . '/plugins/jquery_ui/jquery-ui.min.js')   
               
            ->prependFile($this->basePath() . '/plugins/bootstrap-inputmask/jquery.inputmask.js')
            ->prependFile($this->basePath() . '/js/bootstrap-filestyle.js')
            
            ->prependFile($this->basePath() . '/js/jQuery-2.1.3.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body class="skin-blue sidebar-mini wysihtml5-supported sidebar-collapse">
        
        <div class="wrapper">
<?php echo $this->partial("layout/topo", array("sistema" => $sistema, "app" => $app, "usuario" => $usuario, "sistema_arquivo_logo" => $sistema_arquivo_logo)); ?>
        <?php echo $this->partial("layout/menu", array("sistema" => $sistema, "app" => $app, "usuario" => $usuario, "sistema_arquivo_logo" => $sistema_arquivo_logo));?>
     <div class="content-wrapper">
         <?php
                        $botoes = $sm->get("button");
                        echo $botoes->render($this);
                    ?>
            <section class="content">
            <div class="row">
        <div class="col-md-12" id="idMessage">
<?php 
if ($this->flashMessenger()->hasErrorMessages()) {
    $errors = $this->flashMessenger()->getErrorMessages();
?>
    <div class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul>
<?php foreach ($errors as $erro) { ?>
            <li><?php echo $erro; ?></li>
<?php } ?>
        </ul>
    </div>
<?php } ?>
<?php
if ($this->flashMessenger()->hasSuccessMessages()) {
    $success = $this->flashMessenger()->getSuccessMessages();
?>
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul>
<?php foreach ($success as $sucesso) { ?>
            <li><?php echo $sucesso; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
if ($this->flashMessenger()->hasCurrentErrorMessages()) {
    $errors = $this->flashMessenger()->getCurrentErrorMessages();
?>
    <div class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul>
<?php foreach ($errors as $erro) { ?>
            <li><?php echo $erro; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
    $success = $this->flashMessenger()->getCurrentSuccessMessages();
?>
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul>
<?php foreach ($success as $sucesso) { ?>
            <li><?php echo $sucesso; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
$this->flashMessenger()->clearMessages();
$this->flashMessenger()->clearCurrentMessages();

$this->flashMessenger()->clearMessagesFromContainer();
$this->flashMessenger()->clearCurrentMessagesFromContainer();
?>
    </div>
</div>
                    
                    
                    <?php echo $this->content; ?>
                        </section>
         <?php echo $this->partial("layout/menu2");?>
         
         <?php echo $this->inlineScript() 
                 
                 
                ->prependFile($this->basePath() . '/plugins/jQueryUI/jquery-ui-1.10.3.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ?>
            </div>
            <?php echo $this->partial("layout/rodape");?>
            </div>
    </body>
</html>
