<?php
$info_system = false;
$app = $this->getHelperPluginManager()->getServiceLocator()->get("AplicacaoFachada");
if ($app) {
    $xml = $app->getInfoSistema();
    $info_system = \Marabaixo\Util::xml_to_array($xml);
}
$sistema_nome = $id_arquivo = "";
if ($info_system) { 
    if (isset($info_system["data"]["config"]["sistema"]["nome"])) {
        $sistema_nome = $info_system["data"]["config"]["sistema"]["nome"];
    }
    if (isset($info_system["data"]["config"]["sistema"]["id_arquivo_logo"])) {
        $id_arquivo = $info_system["data"]["config"]["sistema"]["id_arquivo_logo"];
    }
}

echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
<?php if ($sistema_nome) { ?>
        <?php echo $this->headTitle($sistema_nome)->setSeparator(' - ')->setAutoEscape(false) ?>
<?php } ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/skins/_all-skins.min.css')
                ->prependStylesheet($this->basePath() . '/css/AdminLTE.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="skin-blue sidebar-collapse login-page">
        <div class="login">
        <?php 
if ($this->flashMessenger()->hasErrorMessages()) {
    $errors = $this->flashMessenger()->getErrorMessages();
?>
    <div class="alert alert-warning" role="alert">
        <ul>
<?php foreach ($errors as $erro) { ?>
            <li><?php echo $erro; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
if ($this->flashMessenger()->hasSuccessMessages()) {
    $success = $this->flashMessenger()->getSuccessMessages();
?>
    <div class="alert alert-info" role="alert">
        <ul>
<?php foreach ($success as $sucesso) { ?>
            <li><?php echo $sucesso; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }

if ($this->flashMessenger()->hasCurrentErrorMessages()) {
    $errors = $this->flashMessenger()->getCurrentErrorMessages();
?>
    <div class="alert alert-warning" role="alert">
        <ul>
<?php foreach ($errors as $erro) { ?>
            <li><?php echo $erro; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
    $success = $this->flashMessenger()->getCurrentSuccessMessages();
?>
    <div class="alert alert-info" role="alert">
        <ul>
<?php foreach ($success as $sucesso) { ?>
            <li><?php echo $sucesso; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
$this->flashMessenger()->clearMessages();
$this->flashMessenger()->clearCurrentMessages();

$this->flashMessenger()->clearMessagesFromContainer();
$this->flashMessenger()->clearCurrentMessagesFromContainer();
?>
                    <?php echo $this->content; ?> 
            </div>
    </body>
</html>