<aside class="control-sidebar control-sidebar-dark">                
        
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-birthday-tab" data-toggle="tab"><i class="fa fa-birthday-cake"></i></a></li>
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-comments-o"></i></a></li>
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-birthday-tab">
            <h3 class="control-sidebar-heading">Aniversariantes</h3>
            <ul class='control-sidebar-menu'>
              <li>
                <a href='javascript::;'>
                  <img src="<?php echo $this->basePath();?>/img/avatar.jpg" class="menu-icon" alt="" />
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Zé luis</h4>
                    <p>23/06/2015 - 50 Anos</p>
                  </div>
                </a>
              </li>
              <li>
                <a href='javascript::;'>
                  <img src="<?php echo $this->basePath();?>/img/user7-128x128.jpg" class="menu-icon" alt="" />
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Usuario 1</h4>
                    <p>23/06/2015 - 50 Anos</p>
                  </div>
                </a>
              </li>
              <li>
                <a href='javascript::;'>
                  <img src="<?php echo $this->basePath();?>/img/user5-128x128.jpg" class="menu-icon" alt="" />
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Usuario 2</h4>
                    <p>23/06/2015 - 50 Anos</p>
                  </div>
                </a>
              </li>
              <li>
                <a href='javascript::;'>
                  <img src="<?php echo $this->basePath();?>/img/user3-128x128.jpg" class="menu-icon" alt="" />
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Usuario 3</h4>
                    <p>23/06/2015 - 50 Anos</p>
                  </div>
                </a>
              </li>
            </ul>         
        </div>
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Chat</h3>
            <ul class='control-sidebar-menu'>
              <li>
                <a href='#' id='chat-user'>
                  <img src="<?php echo $this->basePath();?>/img/avatar.png" class="menu-icon" alt="" />
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Francivan</h4>
                    <p><i class="fa fa-circle text-success"></i> Online</p>
                  </div>
                </a>
              </li>
            </ul>         
        </div>
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Configurações</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">            
            <form method="post">
              <h3 class="control-sidebar-heading">Configuração Geral</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Menu de opção 1
                  <input type="checkbox" class="pull-right" checked />
                </label>
                <p>
                  Isso pode fazer isso, isso e issso!
                </p>
              </div>

              
              <h3 class="control-sidebar-heading">Configuração de Chat</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Habilitar notificaçoes.
                  <input type="checkbox" class="pull-right" checked />
                </label>                
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Modo Invisivel.
                  <input type="checkbox" class="pull-right" />
                </label>                
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Deletar historico.
                  <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                </label>                
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside>