<?php 
$info_system = $sistema = $usuario = $sistema_arquivo_logo = false;
$sm = $this->getHelperPluginManager()->getServiceLocator();
$app = $sm->get("AplicacaoFachada");
if ($app) {
    $xml = $app->getInfoSistema();
    $info_system = \Marabaixo\Util::xml_to_array($xml);
    if (isset($info_system["data"]["config"]["sistema"])) {
        $sistema = $info_system["data"]["config"]["sistema"];
        if (isset($sistema["id_arquivo_logo"]) && $sistema["id_arquivo_logo"]) {
            $xml = $app->getInfoArquivo(\Marabaixo\Util::array_to_xml(array("id" => $sistema["id_arquivo_logo"])));
            $sistema_arquivo_logo = \Marabaixo\Util::xml_to_array($xml);
            if (isset($sistema_arquivo_logo["data"])) {
                $sistema_arquivo_logo = $sistema_arquivo_logo["data"];
            }
        }
    }
    
    $sistema_nome = $id_arquivo = "";
    if ($info_system) {
        if($info_system["data"]["config"]["sistema"]){
           $sistema = $info_system["data"]["config"]["sistema"]; 
        }
        if (isset($info_system["data"]["config"]["sistema"]["nome"])) {
            $sistema_nome = $info_system["data"]["config"]["sistema"]["nome"];
        }
        if (isset($info_system["data"]["config"]["sistema"]["id_arquivo_logo"])) {
            $id_arquivo = $info_system["data"]["config"]["sistema"]["id_arquivo_logo"];
        }
    }
    
    $xml = $app->pegaUsuarioLogado();
    $array = \Marabaixo\Util::xml_to_array($xml);
    $style = '';
    if (isset($array["data"]["usuario"])) {
        $style = 'style="top:36px;"';
        $usuario = $array["data"]["usuario"];
    }
}
echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
<?php if ($sistema_nome) { ?>
        <?php echo $this->headTitle($sistema_nome)->setSeparator(' - ')->setAutoEscape(false) ?>
<?php } ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/maintheme/css/theme.css')
                ->prependStylesheet($this->basePath() . '/maintheme/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/AdminLTE.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>


    </head>
    <body class="sidebar-close footer-fixed">
        <?php echo $this->partial("layout/toposistema", array("sistema" => $sistema, "app" => $app, "usuario" => $usuario, "sistema_arquivo_logo" => $sistema_arquivo_logo)); ?>
        <div id="geral" <?php echo $style;?>>
            <div id="content">
            
        <?php 
if ($this->flashMessenger()->hasErrorMessages()) {
    $errors = $this->flashMessenger()->getErrorMessages();
?>
                <div class="alert alert-warning" role="alert" style="z-index: 2; position: relative">
        <ul>
<?php foreach ($errors as $erro) { ?>
            <li><?php echo $erro; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
if ($this->flashMessenger()->hasSuccessMessages()) {
    $success = $this->flashMessenger()->getSuccessMessages();
?>
    <div class="alert alert-info" role="alert" style="z-index: 2; position: relative">
        <ul>
<?php foreach ($success as $sucesso) { ?>
            <li><?php echo $sucesso; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }

if ($this->flashMessenger()->hasCurrentErrorMessages()) {
    $errors = $this->flashMessenger()->getCurrentErrorMessages();
?>
    <div class="alert alert-warning" role="alert" style="z-index: 2; position: relative">
        <ul>
<?php foreach ($errors as $erro) { ?>
            <li><?php echo $erro; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
    $success = $this->flashMessenger()->getCurrentSuccessMessages();
?>
    <div class="alert alert-info" role="alert" style="z-index: 2; position: relative">
        <ul>
<?php foreach ($success as $sucesso) { ?>
            <li><?php echo $sucesso; ?></li>
<?php } ?>
        </ul>
    </div>
<?php }
$this->flashMessenger()->clearMessages();
$this->flashMessenger()->clearCurrentMessages();

$this->flashMessenger()->clearMessagesFromContainer();
$this->flashMessenger()->clearCurrentMessagesFromContainer();
?>          <div class="container-fluid">
                    <?php echo $this->content; ?> 
            </div>
                </div>
            <footer class="inner">
                    <div class="footer-inner">
                            <div class="pull-left">
                                    Copyright © 2016 by <a href="http://www.marabaixo.com.br/" target="_blank">Marabaixo System</a>.
                            </div>
                            <div class="pull-right">
                            </div>
                    </div>
                
            </footer>
             </div>
            
    </body>
</html>