<div class="box">
    <div class="box-body">
        <table class="table table-hover">
                <thead>
                    <tr>
                      <th>ID</th>
                      <th>Data</th>
                      <th>Descrição</th>
                      <th>Tipo</th>
                      <th><span class="pull-right">Ações</span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td>1</td>
                      <td>24/08/2015  </td>
                      <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nibh lacus, lobortis nec hendrerit a, hendrerit eu nibh. Nullam nibh purus, dignissim sit amet commodo non, porttitor quis ipsum. Aliquam scelerisque dolor et risus mollis ullamcorper. </td>
                      <td>Atestados</td>
                      <td>
                        
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                        
                      </td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>24/08/2015 </td>
                      <td>Donec in est at libero luctus mollis ac dignissim mi. Phasellus id sem non diam pretium tristique ut quis lectus. Mauris justo erat, tempor in vehicula nec, commodo sed neque. Ut gravida interdum libero, vel molestie est mollis sed. Nulla quis libero ante, quis blandit massa. Suspendisse ac arcu ante, ut aliquet lorem. Cras a ante ac felis facilisis mattis in sit amet lacus. Nam in eros erat, ut vehicula erat. Aenean vitae ligula id neque molestie vulputate nec sed felis.  </td>
                      <td>Certidões</td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    <tr>
                    <tr>
                      <td>3</td>
                      <td>28/09/2015</td>
                      <td>Donec purus justo, auctor eu viverra non, faucibus vel arcu. Duis bibendum lorem sollicitudin neque posuere interdum. Proin purus massa, vulputate non fermentum quis, faucibus aliquam libero. Fusce sodales volutpat sagittis. Vivamus accumsan felis et urna mattis viverra. Proin eu arcu lectus, ut faucibus orci. Quisque in mi in massa rhoncus porttitor sed vel diam.  </td>
                      <td>Abertura documentação</td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                </tbody>
        </table>
    </div>
    <div class="box-footer clearfix">
        
    </div>
</div>