<div class="box">
    <div class="box-body">
        <table class="table table-hover">
                <thead>
                    <tr>
                      <th>Número</th>
                      <th>Valor</th>
                      <th>Data</th>
                      <th>Prazo</th>
                      <th><span class="pull-right">Ações</span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td>01 </td>
                      <td>10.000,00 </td>
                      <td>11/07/2014</td>
                      <td><span class="label label-success">150</span></td>
                      <td>
                        
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                        
                      </td>
                    </tr>
                    <tr>
                      <td>219</td>
                      <td>20.000,00 </td>
                      <td>11/07/2014</td>
                      <td><span class="label label-warning">150 </span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>657</td>
                      <td>30.000,00 </td>
                      <td>11/07/2014</td>
                      <td><span class="label label-primary">180</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    
                </tbody>
        </table>
    </div>
    <div class="box-footer clearfix">
        
    </div>
</div>