<div class="box">
    <div class="box-body">
        <table class="table table-hover">
                <thead>
                    <tr>
                      <th>Empresa</th>
                      <th>Habilitação</th>
                      <th>Nota técnica</th>
                      <th>Nota de preço</th>
                      <th>Nota final</th>
                      <th>Staus</th>
                      <th><span class="pull-right">Ações</span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td>Concorrente B</td>
                      <td>S</td>
                      <td>10.00 </td>
                      <td>10.00 </td>
                      <td>10.00 </td>
                      <td><span class="label label-success">Aprovado</span></td>
                      <td>
                        
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                        
                      </td>
                    </tr>
                    <tr>
                      <td>Concorrente A</td>
                      <td>N</td>
                      <td>5.00 </td>
                      <td>5.00 </td>
                      <td>5.00 </td>
                      <td><span class="label label-info">Classificado</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>Parceira A</td>
                      <td>N</td>
                      <td>3.00 </td>
                      <td>3.00 </td>
                      <td>3.00 </td>
                      <td><span class="label label-danger">Desclassificado</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>Nossa Empresa</td>
                      <td>N</td>
                      <td>2.20</td>
                      <td>2.20</td>
                      <td>2.20</td>
                      <td><span class="label label-danger">Desclassificado</span></td>
                      <td>
                        <div class="btn-group pull-right" role="group">
                          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cog"></i>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-search-minus"></i> Visualizar</a></li>
                            <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                </tbody>
        </table>
    </div>
    <div class="box-footer clearfix">
        
    </div>
</div>