<?php
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
    $("#descricao").focus();
});
<?php
$this->inlineScript()->captureEnd();

$form = $this->form;
$form->setAttribute('action', $this->url(null, array(), true));
$form->setAttribute('class', "form-horizontal");

$form->prepare();
?>
<div class="row">
<div class="col-md-12">
<?php
echo $this->form()->openTag($form);
?>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Cadastro de Modulo</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <?php 
$input = $form->get("id_grupo"); echo $this->formInput($input); 
echo $form->showInput("descricao", $this, array("col-width" => 4)); 
echo $form->showInput("chave", $this, array("col-width" => 4)); 
echo $form->show("Select", "admin", $this, array("col-width" => 4)); 
echo $form->show("Select", "status", $this, array("col-width" => 4)); 
?>
        <div class="form-group">
            <label for="" class="col-sm-2 control-label"></label>
            <div class="controls">
                <div class="col-sm-4">
<?php
$input = $form->get("submit");   
echo $this->formInput($input); 
?>
                </div>
            </div>
        </div>
        </div><!-- /.box-body -->
        <div class="box-footer clearfix">
        </div>
    </div>
<?php
echo $this->form()->closeTag();
?>
</div>
</div>