<div class="row">
    <form action="" method="post" class="form-horizontal" id="pesquisa_form">
<div class="col-md-12">
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Formulário de Pesquisa</h3>
    </div><!-- /.box-header -->
    <div class="box-body"> 
    
        <div class="form-group">
            <label for="pesquisa_descricao" class="col-sm-2 control-label">Descrição: </label>
            <div class="controls">
                <div class="col-sm-4">
                    <input type="text" name="pesquisa_descricao" id="pesquisa_descricao" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["pesquisa_descricao"]; ?>" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="descricao" class="col-sm-2 control-label"></label>
            <div class="controls">
                <div class="col-sm-4">
                    <input type="submit" value="Procurar" class="btn btn-primary" />
                    <input type="button" value="Limpar" class="btn btn-default" id="pesquisa_btn_limpar" />
                </div>
            </div>
        </div>

    </div>
</div>
</div>
</form>
    

        
<div class="col-md-12">
    <div class="box">
    <div class="box-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr class="titulo">
                    <th width="60px">ID</th>
                    <th>Descrição</th>
                    <th>Ícone</th>
                    <th>Ordem</th>
                    <th class="btn_titulo"><span class="pull-right">Ferramentas</span></th>
                </tr>
            </thead>
            <tbody>
<?php if (isset($this->result["registros"])) { ?>
<?php 
foreach ($this->result["registros"] as $registro) {
    $txt_id = $txt_descricao = $txt_icone = $txt_ordem = "--";
    if (isset($registro["id"]) && $registro["id"]) {
        $txt_id = $registro["id"]; 
        $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
    }
    if (isset($registro["descricao"]) && $registro["descricao"]) { $txt_descricao = $registro["descricao"]; }
    if (isset($registro["icone"]) && $registro["icone"]) { $txt_icone = $registro["icone"]; }
    if (isset($registro["ordem"]) && $registro["ordem"]) { $txt_ordem = $registro["ordem"]; }
?>
            <tr>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_id; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_descricao; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_icone; ?></a></td>
                <td><a href="<?php echo $url_view; ?>"><?php echo $txt_ordem; ?></a></td>
                <td>
                    <div class="btn-group pull-right" role="group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fa fa-cog"></i>
                        </button>
                        <ul class="dropdown-menu">
                          <li><a title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i> Visualizar</a></li>
                          <li><a title="Editar" href="<?php echo $this->url(null, array("action" => "editar", "id" => $txt_id), true); ?>"><i class="fa fa-cogs"></i> Editar</a></li>
                          <li><a class="link_confirma" title="Excluir" href="<?php echo $this->url(null, array("action" => "excluir", "id" => $txt_id), true); ?>"><i class="fa fa-trash-o"></i> Excluir</a></li>
                          <li><a title="Vincular Módulos" href="<?php echo $this->url(null, array("action" => "controller", "id" => $txt_id), true); ?>"><i class="fa fa-check-circle-o"></i> Vincular Módulos</a> </li>
                        </ul>
                      </div>
                </td>
            </tr>
<?php } ?>
<?php } else { ?>
            <tr>
                <td colspan="4"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
            </tr>
<?php } ?>
            </tbody>
        </table>
            </div><!-- /.box-body -->
    <div class="box-footer clearfix">
        <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
    </div>
</div>
    </div>
    </div>

