<?php
$txt_id = $txt_descricao = $txt_icone = $txt_ordem = "--";
if (isset($this->result["id"])) { $txt_id = $this->result["id"]; }
if (isset($this->result["descricao"])) { $txt_descricao = $this->result["descricao"]; }
if (isset($this->result["icone"])) { $txt_icone = $this->result["icone"]; }
if (isset($this->result["ordem"])) { $txt_ordem = $this->result["ordem"]; }
?>

<div class="row mt">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Componente</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>ID: </dt>
                    <dd><?php echo $txt_id; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição: </dt>
                    <dd><?php echo $txt_descricao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ícone: </dt>
                    <dd><?php echo $txt_icone; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ordem: </dt>
                    <dd><?php echo $txt_ordem; ?></dd>
                </dl>
            </div><!-- /.box-body -->
            <div class="box-footer clearfix">
            </div>
        </div>
    </div>
</div>