<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$app = $sm->get("AplicacaoFachada");

//validando Estabelecimento de saude
$rs = $app->getEstabelecimentoSaudeAtual(array());
$txt_estabelecimento_saude = "--";
if (isset($rs) && !empty($rs)) {    
    $txt_estabelecimento_saude = $rs['data']['tostring']; 
    ?>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Estabelecimento de Saúde</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <dl class="dl-horizontal">
            <dt>Estabelecimento de Saúde Atual:</dt>
            <dd><?php echo $txt_estabelecimento_saude; ?></dd>
        </dl>
    </div>
</div>
<?php
}