<?php
$txt_id = $txt_ordem = $txt_descricao = $txt_nome_classe = $txt_status = "--";
if (isset($this->result)) {
    $registro = $this->result;
    
    if (isset($registro["id"]) && $registro["id"]) {
        $txt_id = $registro["id"]; 
        $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
    }
    if (isset($registro["tostring"]) && $registro["tostring"]) { $txt_descricao = $registro["tostring"]; }
    if (isset($registro["ordem"]) && $registro["ordem"]) { $txt_ordem = $registro["ordem"]; }
    if (isset($registro["nome_classe"]) && $registro["nome_classe"]) { $txt_nome_classe = $registro["nome_classe"]; }
    if (isset($registro["ativo"])) {
        $txt_status = "INATIVO";
        if ((int)$registro["ativo"]) { $txt_status = "ATIVO"; }
    }
}
?>
<div class="row">
<div class="col-md-12">
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Visualizar Menu</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <dl class="dl-horizontal">
            <dt>ID: </dt>
            <dd><?php echo $txt_id; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Ordem: </dt>
            <dd><?php echo $txt_ordem; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Descrição: </dt>
            <dd><?php echo $txt_descricao; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Nome da Classe: </dt>
            <dd><?php echo $txt_nome_classe; ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Status: </dt>
            <dd><?php echo $txt_status; ?></dd>
        </dl>
    </div>
</div>
</div>
</div>