<?php
$campo_item = $this->campo_item;

$form = $this->form;
$form->setAttribute('action', $this->url(null, array(), true));
$form->setAttribute('class', "form-horizontal");
$form->prepare();
?>
<div class="row">
    <?php include("documentotipo.phtml"); ?>
    <div class="col-md-12">
        <?php
        echo $this->form()->openTag($form);
        ?>
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Cadastro de Campo de Tipo de Documento</h3>
            </div><!-- /.box-header -->
            <div class="box-body">

                <div class="col-sm-7">
                    <?php
                    $obj = $form->get("id");
                    echo $this->formInput($obj);
                    $obj = $form->get("documento_campo_tipo_chave");
                    echo $obj->render($this);
                    echo $form->showInput("entidade", $this, array("col-width" => 3));
                    echo $form->showInput("nome", $this, array("col-width" => 8));
                    echo $form->showInput("descricao", $this, array("col-width" => 8));
                    echo $form->show("Number", "tamanho", $this, array("col-width" => 3));
                    echo $form->show("Select", "ordem", $this, array("col-width" => 3));
                    echo $form->show("Select", "obrigatorio", $this, array("col-width" => 3));
                    echo $form->show("Select", "mostrar_listagem", $this, array("col-width" => 3));
                    echo $form->show("Select", "to_string", $this, array("col-width" => 3));
                    echo $form->show("Select", "filtro", $this, array("col-width" => 3));
                    ?>
                    <div class="form-group">
                        <label for="" class="col-sm-4 control-label"></label>
                        <div class="controls">
                            <div class="col-sm-8">
                                <?php
                                $obj = $form->get("submit");
                                echo $this->formInput($obj);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-5" id="formulario_listagem" style="display:none;">
                    <div class="row">
                        <div class="box">
                            <div class="box-header with-border">
                                <div class="row">
                                    <div class="col-lg-7"><h3 class="box-title">Ítens da Listagem</h3></div>
                                    <div class="col-lg-5">
                                        <div class="text-right">
                                            <input type="button" value="Adicionar" id="add_listagem" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="box-body">
                                <div class="col-md-12" id="mensagem_lista">
                                </div>
                                <div id="form_listagem_item" style="display:none;">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label" for="listagem_chave">Chave:</label>            
                                        <div class="controls">
                                            <div class="col-sm-4">
                                                <input type="text" name="listagem_chave" maxlength="100" class="form-control col-sm-4" id="listagem_chave" value="">                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label" for="listagem_descricao">Descrição:</label>            
                                        <div class="controls">
                                            <div class="col-sm-8">
                                                <input type="text" name="listagem_descricao" maxlength="100" class="form-control col-sm-4" id="listagem_descricao" value="">                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label" for=""></label>            
                                        <div class="controls">
                                            <div class="col-sm-8">
                                                <input type="button" value="Salvar" id="btn_listagem_salvar" class="btn btn-primary" />
                                                <input type="button" value="Cancelar" id="btn_listagem_cancelar" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="box with-border">
                                    <div class="box-body">
                                        <table class="table table-striped table-hover">
                                            <thead>
                                                <tr class="titulo">
                                                    <th>Chave</th>
                                                    <th>Descrição</th>
                                                    <th class="btn_titulo"></th>
                                                </tr>
                                            </thead>
                                            <tbody id="body_listagem">
                                                <?php
                                                if ($campo_item && count($campo_item)) {
                                                    foreach ($campo_item as $chave => $descricao) {
                                                        ?>
                                                        <tr>
                                                    <input type="hidden" name="campo_item[<?php echo $chave; ?>]" class="campo_item" value="<?php echo $descricao; ?>" />
                                                    <td class="td_chave"><?php echo $chave; ?></td>
                                                    <td class="td_descricao"><?php echo $descricao; ?></td>
                                                    <td>
                                                        <div class="btn-group pull-right">
                                                            <a class="btn btn-default btn_listagem_excluir" title="Excluir" href="#"><i class="fa fa-trash-o"></i></a>
                                                        </div>
                                                    </td>
                                                    </tr>                                                
                                                <?php }
                                            } else { ?>
                                                <tr>
                                                    <td colspan="3" class="listagem_nenhum text-center">NENHUM REGISTRO</td>
                                                </tr>
                                            <?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".entidade_row").hide();
        $("#documento_campo_tipo_chave").change(function () {
            $(".entidade_row, #formulario_listagem").hide();
            if ($(this).val() == "DM") { //dominio
                $(".entidade_row").show();
            }
            if ($(this).val() == "LS") { //itens
                $("#formulario_listagem").show();
            }
        }).change();
        $("#add_listagem").click(function () {
            limpaListagemErro();
            $(this).hide();
            $("#listagem_chave, #listagem_descricao").val("");
            $("#form_listagem_item").show();
            $("#listagem_chave").focus();
        });
        $("#btn_listagem_cancelar").click(function () {
            limpaListagemErro();
            $("#add_listagem").show();
            $("#form_listagem_item").hide();
        });
        $("#form_listagem_item").keypress(function (ev) {
            if (ev.which == 13) { //enter
                ev.preventDefault();
                $("#btn_listagem_salvar").click();
                return false;
            }
            return true;
        });
        $("#form_listagem_item").keydown(function (ev) {
            if (ev.which == 27) { //esc
                ev.preventDefault();
                $("#btn_listagem_cancelar").click();
                return false;
            }
            return true;
        });
        $("#btn_listagem_salvar").click(function () {
            limpaListagemErro();
            try {
                var chave = $("#listagem_chave").val();
                var descricao = $("#listagem_descricao").val();
                if (!(chave && chave.length)) {
                    throw {"message": "Falha ao Salvar, Campo Chave Inválido!"};
                }
                if (!(descricao && descricao.length)) {
                    throw {"message": "Falha ao Salvar, Campo Descrição Inválido!"};
                }

                chave = chave.toUpperCase();
                descricao = descricao.toUpperCase();

                var objs = $(".td_chave");
                if (objs.length) {
                    $.each(objs, function (idc, obj) {
                        if (chave == $(obj).text()) {
                            throw {"message": "Falha ao Salvar, Chave Já Cadastrada!"};
                        }
                    });
                }

                var objs = $(".td_descricao");
                if (objs.length) {
                    $.each(objs, function (idc, obj) {
                        if (descricao == $(obj).text()) {
                            throw {"message": "Falha ao Salvar, Descrição Já Cadastrada!"};
                        }
                    });
                }

                $(".listagem_nenhum").remove();

                var tr = $("<tr>").appendTo($("#body_listagem"));
                $("<input>", {"type": "hidden", "class": "campo_item", "name": "campo_item[" + chave + "]", "value": descricao}).appendTo(tr);
                var td = $("<td>", {"class": "td_chave", "text": chave}).appendTo(tr);
                var td = $("<td>", {"class": "td_descricao", "text": descricao}).appendTo(tr);
                var td_button = $("<td>").appendTo(tr);
                var div = $('<div class="btn-group pull-right">').appendTo(td_button);
                $('<a class="btn btn-default btn_listagem_excluir" title="Excluir" href="#"><i class="fa fa-trash-o"></i></a>').appendTo(div);

                $("#btn_listagem_cancelar").click();
            } catch (e) {
                addListagemErro(e.message);
            }
        });

        $("#body_listagem").delegate(".btn_listagem_excluir", "click", function () {
            limpaListagemErro();
            try {
                var tr = $(this).parents("tr");
                if (!(tr && tr.length)) {
                    throw {"message": "Falha ao Excluir, Dados Inválidos!"};
                }

                tr.remove();

                var objs = $("#body_listagem .campo_item");
                if (!(objs && objs.length)) {
                    $('<tr><td colspan="3" class="listagem_nenhum text-center">NENHUM REGISTRO</td><tr>').appendTo($("#body_listagem"));
                }

            } catch (e) {
                addListagemErro(e.message);
            }
        });
        $(".form-control").first().focus().select();

        function addListagemErro(erro) {
            var alert = $('<div class="alert alert-warning" role="alert">').appendTo($("#mensagem_lista"));
            var ul = $("<ul>").appendTo(alert);
            $("<li>" + erro + "</li>").appendTo(ul);
        }

        function limpaListagemErro() {
            $("#mensagem_lista").children().remove();
        }
    });
</script>