<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array(), true));
$form->setAttribute('class', "form-horizontal");
$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <?php
        echo $this->form()->openTag($form);
        ?>
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Ativar/Desativar Servidor</h3>
            </div><!-- /.box-header -->
            <div class="box-body">

                <?php
                $input = $form->get("id");
                echo $this->formInput($input);
                echo $this->formLabel($form->get('servidor_situacao'));
                echo $this->formElement($form->get('servidor_situacao'));
                ?>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label"></label>
                    <div class="controls">
                        <div class="col-sm-4">
                            <?php
                            echo $this->formLabel($form->get('motivo'));
                            $input = $form->get("motivo");
                            echo $this->formTextArea($input);
                            ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label"></label>
                    <div class="controls">
                        <div class="col-sm-4">
                            <?php
                            $input = $form->get("submit");
                            echo $this->formInput($input);
                            ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>