<div class="row">
    <form action="" method="post" class="form-horizontal" id="pesquisa_form" style="display:none">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h4>Formulário de Pesquisa</h4>
                </div>
                <div class="box-body">

                    <div class="form-group">
                        <label for="filtro_nome" class="col-sm-2 control-label">Nome: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="text" name="filtro_nome" id="filtro_nome" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_nome"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_matricula" class="col-sm-2 control-label">Matrícula: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="text" name="filtro_matricula" id="filtro_matricula" class="form-control pesquisa_field" value="<?php echo $this->pesquisa_dados["filtro_matricula"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_data_ocorrencia" class="col-sm-2 control-label">Data Ocorrência: </label>
                        <div class="controls">
                            <div class="col-sm-2">
                                <input type="text" name="filtro_data_ocorrencia" id="filtro_data_ocorrencia" class="form-control pesquisa_field mask_data" value="<?php echo $this->pesquisa_dados["filtro_data_ocorrencia"]; ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="filtro_tipo_ocorrencia" class="col-sm-2 control-label">Tipo de Ocorrência: </label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <select name="filtro_tipo_ocorrencia" id="filtro_tipo_ocorrencia" class="form-control pesquisa_field">
                                    <option value="" <?php echo (!$this->pesquisa_dados["filtro_tipo_ocorrencia"]) ? "selected" : ""; ?>>==> SELECIONE <==</option>
                                    <?php
                                    foreach ($this->ocorrencia_tipo as $ot) {                                      
                                       
                                        extract($ot);
                                        ?>
                                        <option value="<?php echo $chave; ?>" <?php echo ($this->pesquisa_dados["filtro_tipo_ocorrencia"] == $chave) ? "selected" : ""; ?>><?php echo $tostring; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="descricao" class="col-sm-2 control-label"></label>
                        <div class="controls">
                            <div class="col-sm-4">
                                <input type="submit" value="Procurar" class="btn btn-primary" />
                                <input type="button" value="Limpar" class="btn btn-default" id="pesquisa_btn_limpar" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
            </div>
            <div class="box-body">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr class="titulo">
                            <th width="60px">ID</th>
                            <th>Servidor</th>
                            <th>Servidor Responsável</th>
                            <th>Data Ocorrência</th>
                            <th>Tipo Ocorrência</th>
                            <th>Motivo</th>
                            <th class="btn_titulo"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (isset($this->result["registros"])) { 
                               ?>
                            <?php
                            foreach ($this->result["registros"] as $registro) {
                                extract($registro);
                                
                                $servidor_ref = $this->servidor_ref['data']['usuario']['tostring'];                                
                                
                                
                                $servidor = $id_servidor['usuario']['tostring'];
                                
                                if (isset($registro["id"]) && $registro["id"]) {
                                    $txt_id = $registro["id"];
                                    $url_view = $this->url(null, array("action" => "view", "id" => $txt_id), true);
                                }
                                ?>
                                <tr>
                                    <td><a href="<?php echo $url_view; ?>"><?php if($id){echo $id;}else{echo'--';} ?></a></td>                                  
                                    <td><a href="<?php echo $url_view; ?>"><?php if($servidor){echo $servidor;}else{echo'--';} ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php if($servidor_ref){echo $servidor_ref;}else{echo '--';}?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php if($data_servidor_ocorrencia){echo $data_servidor_ocorrencia;}else{echo '--';} ?></a></td>                                    
                                    <td><a href="<?php echo $url_view; ?>"><?php if($id_servidor_ocorrencia_tipo){echo $id_servidor_ocorrencia_tipo['tostring'];}else{echo'--';}; ?></a></td>
                                    <td><a href="<?php echo $url_view; ?>"><?php if($servidor_ocorrencia_motivo){echo $servidor_ocorrencia_motivo;}else{echo'--';}?></a></td>
                                    <td>
                                        <div class="btn-group pull-right">
                                            <a class="btn btn-default" title="Visualizar" href="<?php echo $url_view; ?>"><i class="fa fa-search"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="9"><div class="text-center">NENHUM REGISTRO LOCALIZADO!</div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="box-footer clearfix">
                <?php echo $this->partial("layout/pagination", array("result" => $this->result)); ?>
            </div>
        </div>

    </div>
</div>