
    <form class="form-horizontal" role="form" action="">
    
        <ol class="breadcrumb col-md-8 well-sm">
                <li><i class="fa fa-home"></i> Inicio</li>
                <li><i class="fa fa-users"></i> Funcionario</li>
                <li><a href="">Inserir</a></li>
        </ol>
        <div class="pull-right">
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
            <button type="reset" class="btn btn-danger"><i class="fa fa-remove"></i> Limpar</button>
            <a href="" class="btn btn-default"><i class="fa fa-reply"></i> Voltar</a>
        </div>
    <div class="col-lg-12 well">
        <legend>Cadastro de Funcionarios <div class="pull-right"><h5>Campos com "<i class="fa fa-asterisk text-danger"></i>" Obrigatórios</h5></div></legend>
        <div class="form-group">
          <label for="nome" class="col-sm-2 control-label">Nome:</label> <span class="text-danger">*</span>
          <div class="col-sm-4">
              <input type="email" class="form-control" id="nome" required="">
          </div>
        </div>
        <div class="form-group">
          <label for="sobrenome" class="col-sm-2 control-label">Sobrenome:</label>
          <div class="col-sm-4">
              <input type="text" class="form-control" id="sobrenome">
          </div>
        </div>
        <div class="form-group">
          <label for="email" class="col-sm-2 control-label">Email:</label>
          <div class="col-sm-4">
              <input type="email" class="form-control" id="sobrenome">
          </div>
        </div>
        <div class="form-group">
          <label for="data" class="col-sm-2 control-label">Data:</label>
          <div class="col-sm-2">
              <input type="date" class="form-control" id="data">
          </div>
        </div>
    </div>
</form>