
    <div class="col-md-9">
        <ol class="breadcrumb">
            <li><i class="fa fa-users"></i> Funcionario</li>
            <li><a href="">listar</a></li>
        </ol>
    </div>
    <div class="pull-right col-md-3">
            <a href="" class="btn btn-default"><i class="fa fa-plus-square-o"></i> Novo Item</a>
            <a href="" class="btn btn-default"><i class="fa fa-search"></i> Procurar</a>
            <a href="" class="btn btn-default"><i class="fa fa-reply"></i> Voltar</a>
        
    </div>
    <div class="col-md-12">
            <div class="table-responsive">
            <table class="table table-bordered">
                <tr class="titulo">
                      <th><input type="checkbox" name="checkbox" /></th>
                    <th>#</th>
                    <th>Coluna A</th>
                    <th>Coluna B</th>
                    <th>Coluna C</th>
                    <th>
                        
                    </th>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="checkbox" /></td>
                    <td>12</td>
                    <td>Marcos</td>
                    <td>Fernando</td>
                    <td>Zeluis Bautista</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="" class="btn btn-default"><i class="fa fa-upload"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-search"></i></a>
                            <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </div>
                    </td>
                </tr>
            </table>
    </div>
        <center>
            <ul class="pagination">
                <li class="disabled"><a href="#">«</a></li>
                <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
            </ul>
        </center>
        </div>
